"""Curated use cases for classification member pages."""

USE_CASES = {
    # multiclass.py
    "dataviz.classification.multiclass.multiclass_roc_curve_static": "Use when evaluating a multiclass classifier one class at a time; plots one-vs-rest ROC per class with optional macro average and random baseline.",
    "dataviz.classification.multiclass.multiclass_roc_curve_interactive": "Use when evaluating a multiclass classifier one class at a time; plots one-vs-rest ROC per class with optional macro average and random baseline.",
    "dataviz.classification.multiclass.multiclass_pr_curve_static": "Use when comparing one-vs-rest precision-recall trade-offs across classes, especially on imbalanced multiclass problems where ROC looks overly optimistic.",
    "dataviz.classification.multiclass.multiclass_pr_curve_interactive": "Use when comparing one-vs-rest precision-recall trade-offs across classes, especially on imbalanced multiclass problems where ROC looks overly optimistic.",
    "dataviz.classification.multiclass.roc_curve_comparison_static": "Use to overlay ROC curves from several candidate models on one axes and pick the best discriminator by AUC.",
    "dataviz.classification.multiclass.roc_curve_comparison_interactive": "Use to overlay ROC curves from several candidate models on one axes and pick the best discriminator by AUC.",
    "dataviz.classification.multiclass.pr_curve_comparison_static": "Use to compare candidate models on average precision when positives are rare; overlays one PR curve per model.",
    "dataviz.classification.multiclass.pr_curve_comparison_interactive": "Use to compare candidate models on average precision when positives are rare; overlays one PR curve per model.",
    # multiclass_extra.py
    "dataviz.classification.multiclass_extra.per_class_auc_bar_static": "Use to spot weak classes at a glance; bars show per-class one-vs-rest AUC against the 0.5 random line.",
    "dataviz.classification.multiclass_extra.per_class_auc_bar_interactive": "Use to spot weak classes at a glance; bars show per-class one-vs-rest AUC against the 0.5 random line.",
    "dataviz.classification.multiclass_extra.per_class_ap_bar_static": "Use to rank classes by Average Precision and find classes whose ranking quality drags down a multiclass model.",
    "dataviz.classification.multiclass_extra.per_class_ap_bar_interactive": "Use to rank classes by Average Precision and find classes whose ranking quality drags down a multiclass model.",
    "dataviz.classification.multiclass_extra.top_k_accuracy_curve_static": "Use when predictions feed a downstream re-ranker; shows how accuracy grows as the top-K candidate set widens.",
    "dataviz.classification.multiclass_extra.top_k_accuracy_curve_interactive": "Use when predictions feed a downstream re-ranker; shows how accuracy grows as the top-K candidate set widens.",
    "dataviz.classification.multiclass_extra.confusion_sankey_static": "Use to see where examples flow from true to predicted classes; band width shows which confusions dominate.",
    "dataviz.classification.multiclass_extra.confusion_sankey_interactive": "Use to see where examples flow from true to predicted classes; band width shows which confusions dominate.",
    # multilabel.py
    "dataviz.classification.multilabel.multilabel_confusion_grid_static": "Use to audit a multilabel model label by label; small-multiples grid holds one 2x2 confusion matrix per label.",
    "dataviz.classification.multilabel.multilabel_confusion_grid_interactive": "Use to audit a multilabel model label by label; small-multiples grid holds one 2x2 confusion matrix per label.",
    "dataviz.classification.multilabel.label_cooccurrence_heatmap_static": "Use during EDA of multilabel targets to find label pairs that co-occur; supports raw counts or Jaccard normalization.",
    "dataviz.classification.multilabel.label_cooccurrence_heatmap_interactive": "Use during EDA of multilabel targets to find label pairs that co-occur; supports raw counts or Jaccard normalization.",
    "dataviz.classification.multilabel.hamming_subset_accuracy_bar_static": "Use to contrast lenient Hamming accuracy with strict exact-subset accuracy when summarizing a multilabel model.",
    "dataviz.classification.multilabel.hamming_subset_accuracy_bar_interactive": "Use to contrast lenient Hamming accuracy with strict exact-subset accuracy when summarizing a multilabel model.",
    # pr_curve.py
    "dataviz.classification.pr_curve.precision_recall_curve_static": "Use for imbalanced binary problems; plots precomputed precision vs recall with an optional AP value in the legend.",
    "dataviz.classification.pr_curve.precision_recall_curve_interactive": "Use for imbalanced binary problems; plots precomputed precision vs recall with an optional AP value in the legend.",
    # report.py
    "dataviz.classification.report.classification_report_heatmap_static": "Use to replace a text classification report with a scannable heatmap of per-class precision, recall, and F1.",
    "dataviz.classification.report.classification_report_heatmap_interactive": "Use to replace a text classification report with a scannable heatmap of per-class precision, recall, and F1.",
    "dataviz.classification.report.per_class_metrics_bar_static": "Use to compare precision, recall, and F1 side by side per class with grouped bars.",
    "dataviz.classification.report.per_class_metrics_bar_interactive": "Use to compare precision, recall, and F1 side by side per class with grouped bars.",
    "dataviz.classification.report.class_balance_bar_static": "Use before training to check target imbalance, or after to compare predicted class counts against ground truth.",
    "dataviz.classification.report.class_balance_bar_interactive": "Use before training to check target imbalance, or after to compare predicted class counts against ground truth.",
    "dataviz.classification.report.prediction_distribution_static": "Use to see, per true class, how predictions split across predicted classes; a row-normalized view of the confusion matrix.",
    "dataviz.classification.report.prediction_distribution_interactive": "Use to see, per true class, how predictions split across predicted classes; a row-normalized view of the confusion matrix.",
    # roc.py
    "dataviz.classification.roc.roc_curve_static": "Use to assess a binary classifier from precomputed fpr/tpr arrays, with optional AUC label and random-chance reference line.",
    "dataviz.classification.roc.roc_curve_interactive": "Use to assess a binary classifier from precomputed fpr/tpr arrays, with optional AUC label and random-chance reference line.",
    # score_dist.py
    "dataviz.classification.score_dist.score_distribution_by_class_static": "Use to check score separation between true classes; violin, box, or strip views reveal overlap that limits any threshold.",
    "dataviz.classification.score_dist.score_distribution_by_class_interactive": "Use to check score separation between true classes; violin, box, or strip views reveal overlap that limits any threshold.",
    # threshold.py
    "dataviz.classification.threshold.threshold_metric_curve_static": "Use to pick an operating threshold; sweeps precision, recall, F1, accuracy, and specificity across thresholds.",
    "dataviz.classification.threshold.threshold_metric_curve_interactive": "Use to pick an operating threshold; sweeps precision, recall, F1, accuracy, and specificity across thresholds.",
    "dataviz.classification.threshold.ks_statistic_plot_static": "Use in credit scoring to measure class separation; plots class CDFs and marks the maximum KS gap.",
    "dataviz.classification.threshold.ks_statistic_plot_interactive": "Use in credit scoring to measure class separation; plots class CDFs and marks the maximum KS gap.",
    "dataviz.classification.threshold.det_curve_static": "Use for detection or biometric systems; plots FNR vs FPR on a probit scale to spread out low-error operating regions.",
    "dataviz.classification.threshold.det_curve_interactive": "Use for detection or biometric systems; plots FNR vs FPR on log axes to spread out low-error operating regions.",
    "dataviz.classification.threshold.cost_curve_static": "Use when false positives and false negatives carry different costs; finds the threshold minimizing total misclassification cost.",
    "dataviz.classification.threshold.cost_curve_interactive": "Use when false positives and false negatives carry different costs; finds the threshold minimizing total misclassification cost.",
    "dataviz.classification.threshold.net_benefit_curve_static": "Use for decision-curve analysis in clinical or policy settings; compares model net benefit against treat-all and treat-none.",
    "dataviz.classification.threshold.net_benefit_curve_interactive": "Use for decision-curve analysis in clinical or policy settings; compares model net benefit against treat-all and treat-none.",
    # threshold_extra.py
    "dataviz.classification.threshold_extra.f_beta_curve_static": "Use when recall matters more or less than precision; sweeps F-beta for several beta values across thresholds.",
    "dataviz.classification.threshold_extra.f_beta_curve_interactive": "Use when recall matters more or less than precision; sweeps F-beta for several beta values across thresholds.",
    "dataviz.classification.threshold_extra.mcc_curve_static": "Use to choose a threshold with a balanced single-number quality score; MCC vs threshold with the argmax marked.",
    "dataviz.classification.threshold_extra.mcc_curve_interactive": "Use to choose a threshold with a balanced single-number quality score; MCC vs threshold with the argmax marked.",
    "dataviz.classification.threshold_extra.youden_j_curve_static": "Use to find the threshold maximizing sensitivity plus specificity; plots both components and Youden's J.",
    "dataviz.classification.threshold_extra.youden_j_curve_interactive": "Use to find the threshold maximizing sensitivity plus specificity; plots both components and Youden's J.",
    "dataviz.classification.threshold_extra.balanced_accuracy_curve_static": "Use on imbalanced data to pick a threshold by balanced accuracy, the mean of sensitivity and specificity.",
    "dataviz.classification.threshold_extra.balanced_accuracy_curve_interactive": "Use on imbalanced data to pick a threshold by balanced accuracy, the mean of sensitivity and specificity.",
    "dataviz.classification.threshold_extra.cohen_kappa_curve_static": "Use to maximize agreement beyond chance; sweeps Cohen's kappa across thresholds and marks the optimum.",
    "dataviz.classification.threshold_extra.cohen_kappa_curve_interactive": "Use to maximize agreement beyond chance; sweeps Cohen's kappa across thresholds and marks the optimum.",
    "dataviz.classification.threshold_extra.likelihood_ratio_curve_static": "Use in clinical diagnostics to see how LR+ and LR- vary with the cut-off; log scale highlights informative thresholds.",
    "dataviz.classification.threshold_extra.likelihood_ratio_curve_interactive": "Use in clinical diagnostics to see how LR+ and LR- vary with the cut-off; log scale highlights informative thresholds.",
    "dataviz.classification.threshold_extra.predictive_value_curve_static": "Use to show how PPV and NPV shift with prevalence for a test of fixed sensitivity and specificity.",
    "dataviz.classification.threshold_extra.predictive_value_curve_interactive": "Use to show how PPV and NPV shift with prevalence for a test of fixed sensitivity and specificity.",
    # training.py
    "dataviz.classification.training.validation_curve_static": "Use to tune a hyperparameter; plots train and validation score means with std bands over the swept values.",
    "dataviz.classification.training.validation_curve_interactive": "Use to tune a hyperparameter; plots train and validation score means with std bands over the swept values.",
    "dataviz.classification.training.cv_score_boxplot_static": "Use to compare model candidates on cross-validation stability; one box per model over per-fold scores.",
    "dataviz.classification.training.cv_score_boxplot_interactive": "Use to compare model candidates on cross-validation stability; one box per model over per-fold scores.",
    "dataviz.classification.training.training_history_curve_static": "Use to monitor fit quality over epochs; plots loss or metric series with validation curves dashed.",
    "dataviz.classification.training.training_history_curve_interactive": "Use to monitor fit quality over epochs; plots loss or metric series with validation curves dashed.",
}
