"""Curated use cases for classification member pages."""

USE_CASES = {
    # calibration.py
    "dataviz.classification.calibration.calibration_curve_static": "Use to check whether predicted probabilities match observed frequencies, e.g. before trusting scores as risk estimates.",
    "dataviz.classification.calibration.calibration_curve_interactive": "Use to check whether predicted probabilities match observed frequencies, e.g. before trusting scores as risk estimates.",
    "dataviz.classification.calibration.probability_histogram_static": "Use to inspect class separability in predicted probabilities; well-separated peaks indicate a discriminative classifier.",
    "dataviz.classification.calibration.probability_histogram_interactive": "Use to inspect class separability in predicted probabilities; well-separated peaks indicate a discriminative classifier.",
    "dataviz.classification.calibration.probability_density_static": "Use for a smooth per-class view of predicted probability density when histograms are too coarse or noisy.",
    "dataviz.classification.calibration.probability_density_interactive": "Use for a smooth per-class view of predicted probability density when histograms are too coarse or noisy.",
    "dataviz.classification.calibration.brier_score_bar_static": "Compare models or classes on Brier score to rank probability quality; lower bars are better.",
    "dataviz.classification.calibration.brier_score_bar_interactive": "Compare models or classes on Brier score to rank probability quality; lower bars are better.",
    # calibration_extra.py
    "dataviz.classification.calibration_extra.multiclass_calibration_curve_static": "Use to audit one-vs-rest calibration per class in a multiclass problem, one reliability panel per class.",
    "dataviz.classification.calibration_extra.multiclass_calibration_curve_interactive": "Use to audit one-vs-rest calibration per class in a multiclass problem, one reliability panel per class.",
    "dataviz.classification.calibration_extra.calibration_with_confidence_static": "Use when a plain reliability diagram is ambiguous on small data; bootstrap bands show whether deviations are significant.",
    "dataviz.classification.calibration_extra.calibration_with_confidence_interactive": "Use when a plain reliability diagram is ambiguous on small data; bootstrap bands show whether deviations are significant.",
    "dataviz.classification.calibration_extra.platt_isotonic_overlay_static": "Use when choosing a recalibration method by comparing raw, Platt-scaled and isotonic mappings against binned observations.",
    "dataviz.classification.calibration_extra.platt_isotonic_overlay_interactive": "Use when choosing a recalibration method by comparing raw, Platt-scaled and isotonic mappings against binned observations.",
    "dataviz.classification.calibration_extra.sharpness_resolution_decomposition_static": "Use to decompose the Brier score into reliability, resolution and uncertainty to see why probability quality is poor.",
    "dataviz.classification.calibration_extra.sharpness_resolution_decomposition_interactive": "Use to decompose the Brier score into reliability, resolution and uncertainty to see why probability quality is poor.",
    "dataviz.classification.calibration_extra.score_ecdf_by_class_static": "Use to compare full score distributions per class without binning; separated ECDFs signal good ranking power.",
    "dataviz.classification.calibration_extra.score_ecdf_by_class_interactive": "Use to compare full score distributions per class without binning; separated ECDFs signal good ranking power.",
    "dataviz.classification.calibration_extra.score_qq_by_class_static": "Use to spot distributional skew in scores per class by plotting class quantiles against a uniform reference.",
    "dataviz.classification.calibration_extra.score_qq_by_class_interactive": "Use to spot distributional skew in scores per class by plotting class quantiles against a uniform reference.",
    # charts.py
    "dataviz.classification.charts.confusion_matrix_plot": "Use for a quick annotated confusion matrix heatmap of actual vs. predicted class counts.",
    "dataviz.classification.charts.roc_curve": "Use to summarize ranking quality across all thresholds from known fpr/tpr arrays, with optional AUC in the legend.",
    "dataviz.classification.charts.precision_recall_curve": "Use when tuning a classifier's decision threshold to trade off precision against recall, especially on imbalanced data.",
    # confusion_extended.py
    "dataviz.classification.confusion_extended.normalized_confusion_matrix_static": "Use instead of raw counts when classes are imbalanced; normalize by true, pred or all to read recall or precision per class.",
    "dataviz.classification.confusion_extended.normalized_confusion_matrix_interactive": "Use instead of raw counts when classes are imbalanced; normalize by true, pred or all to read recall or precision per class.",
    "dataviz.classification.confusion_extended.confusion_matrix_diff_static": "Compare two models by plotting the element-wise difference of their confusion matrices to see where errors shift.",
    "dataviz.classification.confusion_extended.confusion_matrix_diff_interactive": "Compare two models by plotting the element-wise difference of their confusion matrices to see where errors shift.",
    "dataviz.classification.confusion_extended.error_analysis_grid_static": "Use to isolate which class pairs get confused; shows only off-diagonal mistake rates per true class.",
    "dataviz.classification.confusion_extended.error_analysis_grid_interactive": "Use to isolate which class pairs get confused; shows only off-diagonal mistake rates per true class.",
    # confusion_matrix.py
    "dataviz.classification.confusion_matrix.confusion_matrix_plot_static": "Use for a publication-style confusion matrix heatmap with counts, labels and colorbar.",
    "dataviz.classification.confusion_matrix.confusion_matrix_plot_interactive": "Use for an explorable confusion matrix heatmap with hover values, e.g. in dashboards or notebooks.",
    # decision_boundary.py
    "dataviz.classification.decision_boundary.decision_boundary_plot_static": "Use to visualize how a 2-D classifier partitions feature space, given any predict function over (n, 2) points.",
    "dataviz.classification.decision_boundary.decision_boundary_plot_interactive": "Use to visualize how a 2-D classifier partitions feature space, given any predict function over (n, 2) points.",
    # errors.py
    "dataviz.classification.errors.confidence_by_correctness_histogram_static": "Use to check whether the model is confident when right and uncertain when wrong; overlapping tails flag overconfidence.",
    "dataviz.classification.errors.confidence_by_correctness_histogram_interactive": "Use to check whether the model is confident when right and uncertain when wrong; overlapping tails flag overconfidence.",
    "dataviz.classification.errors.discrimination_threshold_dashboard_static": "Use to pick an operating threshold by viewing precision, recall, F1 and queue rate together across all thresholds.",
    "dataviz.classification.errors.discrimination_threshold_dashboard_interactive": "Use to pick an operating threshold by viewing precision, recall, F1 and queue rate together across all thresholds.",
    "dataviz.classification.errors.misclassification_cluster_heatmap_static": "Use to localize errors by true class and score bin, revealing where in the score range mistakes concentrate.",
    "dataviz.classification.errors.misclassification_cluster_heatmap_interactive": "Use to localize errors by true class and score bin, revealing where in the score range mistakes concentrate.",
    "dataviz.classification.errors.loss_distribution_plot_static": "Use to surface high-loss outlier samples driving log loss, split by true class with the mean marked.",
    "dataviz.classification.errors.loss_distribution_plot_interactive": "Use to surface high-loss outlier samples driving log loss, split by true class with the mean marked.",
    # fairness.py
    "dataviz.classification.fairness.per_segment_metric_bar_static": "Use to audit accuracy, F1, TPR or FPR side by side across demographic or segment groups.",
    "dataviz.classification.fairness.per_segment_metric_bar_interactive": "Use to audit accuracy, F1, TPR or FPR side by side across demographic or segment groups.",
    "dataviz.classification.fairness.fairness_disparity_heatmap_static": "Use to spot which groups deviate from the population mean on fairness metrics such as TPR or selection rate.",
    "dataviz.classification.fairness.fairness_disparity_heatmap_interactive": "Use to spot which groups deviate from the population mean on fairness metrics such as TPR or selection rate.",
    "dataviz.classification.fairness.segment_roc_overlay_static": "Use to expose ranking-performance disparity by overlaying one ROC curve per subgroup.",
    "dataviz.classification.fairness.segment_roc_overlay_interactive": "Use to expose ranking-performance disparity by overlaying one ROC curve per subgroup.",
    "dataviz.classification.fairness.segment_calibration_overlay_static": "Use to check whether probability calibration holds equally well across subgroups.",
    "dataviz.classification.fairness.segment_calibration_overlay_interactive": "Use to check whether probability calibration holds equally well across subgroups.",
    # gain_lift.py
    "dataviz.classification.gain_lift.gain_chart_static": "Use to show what fraction of positives is captured by targeting the top-scored fraction of the population.",
    "dataviz.classification.gain_lift.gain_chart_interactive": "Use to show what fraction of positives is captured by targeting the top-scored fraction of the population.",
    "dataviz.classification.gain_lift.lift_chart_static": "Use to quantify how much better than random each score decile performs, e.g. for campaign targeting.",
    "dataviz.classification.gain_lift.lift_chart_interactive": "Use to quantify how much better than random each score decile performs, e.g. for campaign targeting.",
    "dataviz.classification.gain_lift.cumulative_accuracy_profile_static": "Use to compare the model CAP curve against perfect and random baselines and read the accuracy ratio.",
    "dataviz.classification.gain_lift.cumulative_accuracy_profile_interactive": "Use to compare the model CAP curve against perfect and random baselines and read the accuracy ratio.",
    # model_comparison.py
    "dataviz.classification.model_comparison.metrics_radar_chart_static": "Compare several models across the same metric set at a glance with a radar/spider chart.",
    "dataviz.classification.model_comparison.metrics_radar_chart_interactive": "Compare several models across the same metric set at a glance with a radar/spider chart.",
    "dataviz.classification.model_comparison.pareto_tradeoff_bubble_static": "Compare models on two competing metrics and highlight the Pareto frontier of non-dominated candidates.",
    "dataviz.classification.model_comparison.pareto_tradeoff_bubble_interactive": "Compare models on two competing metrics and highlight the Pareto frontier of non-dominated candidates.",
    "dataviz.classification.model_comparison.critical_difference_diagram_static": "Use to compare classifiers across multiple datasets via average ranks and a critical-difference threshold.",
    "dataviz.classification.model_comparison.critical_difference_diagram_interactive": "Use to compare classifiers across multiple datasets via average ranks and a critical-difference threshold.",
    "dataviz.classification.model_comparison.score_distribution_drift_static": "Use to monitor production models by overlaying reference vs. current score distributions for drift.",
    "dataviz.classification.model_comparison.score_distribution_drift_interactive": "Use to monitor production models by overlaying reference vs. current score distributions for drift.",
    "dataviz.classification.model_comparison.psi_bar_static": "Use to quantify population stability with per-bin PSI contributions and the total PSI against stability tiers.",
    "dataviz.classification.model_comparison.psi_bar_interactive": "Use to quantify population stability with per-bin PSI contributions and the total PSI against stability tiers.",
}
