"""Curated use cases for regression member pages."""

USE_CASES = {
    # mixed_effects
    "dataviz.regression.mixed_effects.random_effect_caterpillar_static": "Use to rank group-level random effects with standard-error bars and see which groups differ significantly from zero.",
    "dataviz.regression.mixed_effects.random_effect_caterpillar_interactive": "Use to rank group-level random effects with standard-error bars and see which groups differ significantly from zero.",
    "dataviz.regression.mixed_effects.random_intercept_slope_scatter_static": "Use to check whether groups with higher random intercepts also show stronger or weaker random slopes.",
    "dataviz.regression.mixed_effects.random_intercept_slope_scatter_interactive": "Use to check whether groups with higher random intercepts also show stronger or weaker random slopes.",
    "dataviz.regression.mixed_effects.group_means_vs_predicted_static": "Use to compare observed group means against mixed-model predicted means to spot groups the model fits poorly.",
    "dataviz.regression.mixed_effects.group_means_vs_predicted_interactive": "Use to compare observed group means against mixed-model predicted means to spot groups the model fits poorly.",
    # multicollinearity
    "dataviz.regression.multicollinearity.vif_bar_static": "Use to flag predictors whose variance inflation factor exceeds a threshold before fitting a linear model.",
    "dataviz.regression.multicollinearity.vif_bar_interactive": "Use to flag predictors whose variance inflation factor exceeds a threshold before fitting a linear model.",
    "dataviz.regression.multicollinearity.condition_index_plot_static": "Use to detect near-collinearity in the design matrix via condition indices, complementing per-feature VIF checks.",
    "dataviz.regression.multicollinearity.condition_index_plot_interactive": "Use to detect near-collinearity in the design matrix via condition indices, complementing per-feature VIF checks.",
    "dataviz.regression.multicollinearity.correlation_heatmap_with_clustering_static": "Use to surface clusters of highly correlated predictors so redundant features can be dropped or combined.",
    "dataviz.regression.multicollinearity.correlation_heatmap_with_clustering_interactive": "Use to surface clusters of highly correlated predictors so redundant features can be dropped or combined.",
    "dataviz.regression.multicollinearity.eigenvalue_scree_predictors_static": "Use to see how much predictor variance concentrates in a few components, a sign of multicollinearity.",
    "dataviz.regression.multicollinearity.eigenvalue_scree_predictors_interactive": "Use to see how much predictor variance concentrates in a few components, a sign of multicollinearity.",
    "dataviz.regression.multicollinearity.tolerance_bar_static": "Use to flag predictors with low tolerance (1/VIF), the reciprocal view of variance inflation.",
    "dataviz.regression.multicollinearity.tolerance_bar_interactive": "Use to flag predictors with low tolerance (1/VIF), the reciprocal view of variance inflation.",
    # prediction
    "dataviz.regression.prediction.prediction_plot_static": "Use to compare predicted against actual values with a perfect-preference reference line for a quick fit-quality check.",
    "dataviz.regression.prediction.prediction_plot_interactive": "Use to compare predicted against actual values with a perfect-prediction reference line for a quick fit-quality check.",
    # prediction_extended
    "dataviz.regression.prediction_extended.pred_vs_actual_hexbin_static": "Use when many points overplot a predicted-vs-actual scatter; the hexbin density reveals where predictions concentrate.",
    "dataviz.regression.prediction_extended.pred_vs_actual_hexbin_interactive": "Use when many points overplot a predicted-vs-actual scatter; the 2-D histogram reveals where predictions concentrate.",
    "dataviz.regression.prediction_extended.pred_vs_actual_density_static": "Use to compare the marginal distributions of actual and predicted values and expose systematic shift or shrinkage.",
    "dataviz.regression.prediction_extended.pred_vs_actual_density_interactive": "Use to compare the marginal distributions of actual and predicted values and expose systematic shift or shrinkage.",
    "dataviz.regression.prediction_extended.prediction_error_histogram_static": "Use to inspect the distribution of prediction errors for bias, skew, or heavy tails, optionally cumulatively.",
    "dataviz.regression.prediction_extended.prediction_error_histogram_interactive": "Use to inspect the distribution of prediction errors for bias, skew, or heavy tails, optionally cumulatively.",
    "dataviz.regression.prediction_extended.prediction_interval_plot_static": "Use to show predictions with an empirical or Gaussian interval band and see which actuals fall outside it.",
    "dataviz.regression.prediction_extended.prediction_interval_plot_interactive": "Use to show predictions with an empirical or Gaussian interval band and see which actuals fall outside it.",
    "dataviz.regression.prediction_extended.error_by_magnitude_plot_static": "Use to check whether errors grow with the size of the target by binning MAE over quantiles of actual values.",
    "dataviz.regression.prediction_extended.error_by_magnitude_plot_interactive": "Use to check whether errors grow with the size of the target by binning MAE over quantiles of actual values.",
    # quantile
    "dataviz.regression.quantile.quantile_regression_band_static": "Use to visualize fitted low/median/high quantile curves against the data when modeling more than the conditional mean.",
    "dataviz.regression.quantile.quantile_regression_band_interactive": "Use to visualize fitted low/median/high quantile curves against the data when modeling more than the conditional mean.",
    "dataviz.regression.quantile.quantile_loss_curve_static": "Use to compare pinball loss across quantile levels when selecting or evaluating quantile-regression models.",
    "dataviz.regression.quantile.quantile_loss_curve_interactive": "Use to compare pinball loss across quantile levels when selecting or evaluating quantile-regression models.",
    "dataviz.regression.quantile.huber_vs_ols_overlay_static": "Use to show how a robust Huber fit diverges from OLS on data containing outliers.",
    "dataviz.regression.quantile.huber_vs_ols_overlay_interactive": "Use to show how a robust Huber fit diverges from OLS on data containing outliers.",
    "dataviz.regression.quantile.weighted_residual_plot_static": "Use to check whether high-weight observations drive residual patterns in weighted or robust fits.",
    "dataviz.regression.quantile.weighted_residual_plot_interactive": "Use to check whether high-weight observations drive residual patterns in weighted or robust fits.",
    # regularization
    "dataviz.regression.regularization.compute_regularization_path": "Use to compute lasso, ridge, or elastic-net coefficient paths over a grid of penalties before plotting them.",
    "dataviz.regression.regularization.lasso_path_static": "Use to see which coefficients shrink to zero as the lasso penalty grows, guiding feature selection.",
    "dataviz.regression.regularization.lasso_path_interactive": "Use to see which coefficients shrink to zero as the lasso penalty grows, guiding feature selection.",
    "dataviz.regression.regularization.ridge_path_static": "Use to see how coefficients shrink smoothly under ridge penalties when keeping all features in the model.",
    "dataviz.regression.regularization.ridge_path_interactive": "Use to see how coefficients shrink smoothly under ridge penalties when keeping all features in the model.",
    "dataviz.regression.regularization.regularization_validation_plot_static": "Use to pick a penalty strength by comparing train and validation scores, with a fold std band when available.",
    "dataviz.regression.regularization.regularization_validation_plot_interactive": "Use to pick a penalty strength by comparing train and validation scores, with a fold std band when available.",
    # residual
    "dataviz.regression.residual.residual_plot_static": "Use as the first residual diagnostic: plot residuals vs fitted values to reveal nonlinearity or heteroscedasticity.",
    "dataviz.regression.residual.residual_plot_interactive": "Use as the first residual diagnostic: plot residuals vs fitted values to reveal nonlinearity or heteroscedasticity.",
    # residual_extended
    "dataviz.regression.residual_extended.residual_histogram_static": "Use to check whether residuals are roughly centered and symmetric, with an optional normal overlay.",
    "dataviz.regression.residual_extended.residual_histogram_interactive": "Use to check whether residuals are roughly centered and symmetric, with an optional normal overlay.",
    "dataviz.regression.residual_extended.residual_density_static": "Use to assess the shape of the residual distribution with a smooth kernel-density estimate.",
    "dataviz.regression.residual_extended.residual_density_interactive": "Use to assess the shape of the residual distribution with a smooth kernel-density estimate.",
    "dataviz.regression.residual_extended.residual_qq_static": "Use to test the normality assumption by plotting residual quantiles against a normal reference line.",
    "dataviz.regression.residual_extended.residual_qq_interactive": "Use to test the normality assumption by plotting residual quantiles against a normal reference line.",
    "dataviz.regression.residual_extended.residual_boxplot_by_group_static": "Use to compare residual spread and bias across categorical groups such as sites, cohorts, or segments.",
    "dataviz.regression.residual_extended.residual_boxplot_by_group_interactive": "Use to compare residual spread and bias across categorical groups such as sites, cohorts, or segments.",
    "dataviz.regression.residual_extended.standardized_residual_plot_static": "Use to flag outlying observations by plotting residuals scaled by their estimated standard deviation.",
    "dataviz.regression.residual_extended.standardized_residual_plot_interactive": "Use to flag outlying observations by plotting residuals scaled by their estimated standard deviation.",
    "dataviz.regression.residual_extended.scale_location_plot_static": "Use to check homoscedasticity by plotting sqrt of absolute standardized residuals against fitted values.",
    "dataviz.regression.residual_extended.scale_location_plot_interactive": "Use to check homoscedasticity by plotting sqrt of absolute standardized residuals against fitted values.",
}
