"""Curated use cases for regression member pages."""

USE_CASES = {
    # residual_features
    "dataviz.regression.residual_features.residual_vs_feature_static": "Use to check whether a single feature still carries structure the model missed; a curved trend in residuals vs that feature signals nonlinearity or a missing interaction.",
    "dataviz.regression.residual_features.residual_vs_feature_interactive": "Use to check whether a single feature still carries structure the model missed; a curved trend in residuals vs that feature signals nonlinearity or a missing interaction.",
    "dataviz.regression.residual_features.partial_residual_plot_static": "Use to inspect the marginal effect of one predictor in an OLS fit while adjusting for the others; curvature suggests the feature needs a nonlinear term.",
    "dataviz.regression.residual_features.partial_residual_plot_interactive": "Use to inspect the marginal effect of one predictor in an OLS fit while adjusting for the others; curvature suggests the feature needs a nonlinear term.",
    "dataviz.regression.residual_features.ccpr_plot_static": "Use to judge where the linear component of one predictor fits well and where residuals spread out, helping spot nonlinearity or heteroscedasticity per feature.",
    "dataviz.regression.residual_features.ccpr_plot_interactive": "Use to judge where the linear component of one predictor fits well and where residuals spread out, helping spot nonlinearity or heteroscedasticity per feature.",
    "dataviz.regression.residual_features.added_variable_plot_static": "Use to decide whether adding a candidate predictor helps an OLS model; a strong slope in the partial-regression scatter means the feature adds information beyond the others.",
    "dataviz.regression.residual_features.added_variable_plot_interactive": "Use to decide whether adding a candidate predictor helps an OLS model; a strong slope in the partial-regression scatter means the feature adds information beyond the others.",
    # selection
    "dataviz.regression.selection.aic_bic_bar_static": "Compare candidate models on AIC and BIC side by side when picking a final specification; lower bars indicate better fit penalized for complexity.",
    "dataviz.regression.selection.aic_bic_bar_interactive": "Compare candidate models on AIC and BIC side by side when picking a final specification; lower bars indicate better fit penalized for complexity.",
    "dataviz.regression.selection.nested_model_comparison_plot_static": "Use when adding terms step by step to see how log-likelihood improves across nested models and where extra parameters stop paying off.",
    "dataviz.regression.selection.nested_model_comparison_plot_interactive": "Use when adding terms step by step to see how log-likelihood improves across nested models and where extra parameters stop paying off.",
    "dataviz.regression.selection.stepwise_selection_path_static": "Use to trace a forward or backward stepwise search step by step, showing how the score evolves as features enter or leave the model.",
    "dataviz.regression.selection.stepwise_selection_path_interactive": "Use to trace a forward or backward stepwise search step by step, showing how the score evolves as features enter or leave the model.",
    "dataviz.regression.selection.forward_selection_score_curve_static": "Use to pick how many features to keep in forward selection by finding the point where adding more features stops improving the score.",
    "dataviz.regression.selection.forward_selection_score_curve_interactive": "Use to pick how many features to keep in forward selection by finding the point where adding more features stops improving the score.",
    "dataviz.regression.selection.best_subset_metric_bar_static": "Compare a fit metric across candidate feature subsets in best-subset selection; the highlighted minimum marks the subset to keep.",
    "dataviz.regression.selection.best_subset_metric_bar_interactive": "Compare a fit metric across candidate feature subsets in best-subset selection; the highlighted minimum marks the subset to keep.",
    # spatial
    "dataviz.regression.spatial.spatial_residual_map_static": "Use to map regression residuals by longitude and latitude to reveal geographic clusters of over- or under-prediction the model missed.",
    "dataviz.regression.spatial.spatial_residual_map_interactive": "Use to map regression residuals by longitude and latitude to reveal geographic clusters of over- or under-prediction the model missed.",
    "dataviz.regression.spatial.moran_scatter_static": "Use to test for spatial autocorrelation by plotting each standardized value against its spatial lag; the slope approximates Moran's I.",
    "dataviz.regression.spatial.moran_scatter_interactive": "Use to test for spatial autocorrelation by plotting each standardized value against its spatial lag; the slope approximates Moran's I.",
    "dataviz.regression.spatial.panel_residual_heatmap_static": "Use to scan panel-data residuals across units and time periods at once, spotting unit-specific bias or temporal drift in the model.",
    "dataviz.regression.spatial.panel_residual_heatmap_interactive": "Use to scan panel-data residuals across units and time periods at once, spotting unit-specific bias or temporal drift in the model.",
    # survival
    "dataviz.regression.survival.km_predicted_vs_observed_static": "Use to validate a survival model by overlaying predicted and observed Kaplan-Meier curves; divergence signals poor calibration of survival probabilities.",
    "dataviz.regression.survival.km_predicted_vs_observed_interactive": "Use to validate a survival model by overlaying predicted and observed Kaplan-Meier curves; divergence signals poor calibration of survival probabilities.",
    "dataviz.regression.survival.cox_residual_plot_static": "Use to diagnose a Cox model by plotting martingale, deviance, or Schoenfeld residuals against time; patterns indicate bad fit or violated assumptions.",
    "dataviz.regression.survival.cox_residual_plot_interactive": "Use to diagnose a Cox model by plotting martingale, deviance, or Schoenfeld residuals against time; patterns indicate bad fit or violated assumptions.",
    "dataviz.regression.survival.proportional_hazards_test_plot_static": "Use to check the Cox proportional-hazards assumption per covariate; bars below the alpha line flag Schoenfeld test violations.",
    "dataviz.regression.survival.proportional_hazards_test_plot_interactive": "Use to check the Cox proportional-hazards assumption per covariate; bars below the alpha line flag Schoenfeld test violations.",
    # transforms
    "dataviz.regression.transforms.boxcox_likelihood_curve_static": "Use to choose a Box-Cox power for the response by reading the profile log-likelihood over lambda and its maximizer.",
    "dataviz.regression.transforms.boxcox_likelihood_curve_interactive": "Use to choose a Box-Cox power for the response by reading the profile log-likelihood over lambda and its maximizer.",
    "dataviz.regression.transforms.yeojohnson_lambda_search_static": "Use to pick a Yeo-Johnson transform for data that include zeros or negatives, reading the optimal lambda from the log-likelihood curve.",
    "dataviz.regression.transforms.yeojohnson_lambda_search_interactive": "Use to pick a Yeo-Johnson transform for data that include zeros or negatives, reading the optimal lambda from the log-likelihood curve.",
    "dataviz.regression.transforms.log_log_diagnostic_static": "Use to test a power-law relationship between x and y; a straight line in log-log space justifies a log-log model and its slope is the exponent.",
    "dataviz.regression.transforms.log_log_diagnostic_interactive": "Use to test a power-law relationship between x and y; a straight line in log-log space justifies a log-log model and its slope is the exponent.",
    "dataviz.regression.transforms.power_transform_residual_panel_static": "Compare residuals-vs-fitted for raw, log, and sqrt transforms side by side to choose the response transform that best stabilizes variance.",
    "dataviz.regression.transforms.power_transform_residual_panel_interactive": "Compare residuals-vs-fitted for raw, log, and sqrt transforms side by side to choose the response transform that best stabilizes variance.",
    # uncertainty
    "dataviz.regression.uncertainty.conformal_interval_plot_static": "Use to audit conformal prediction intervals by viewing the band, predictions, and actuals sorted by prediction; uncovered points reveal weak coverage.",
    "dataviz.regression.uncertainty.conformal_interval_plot_interactive": "Use to audit conformal prediction intervals by viewing the band, predictions, and actuals sorted by prediction; uncovered points reveal weak coverage.",
    "dataviz.regression.uncertainty.jackknife_plus_band_static": "Use to visualize jackknife+ predictive bands around sorted predictions and see where actuals fall outside the interval.",
    "dataviz.regression.uncertainty.jackknife_plus_band_interactive": "Use to visualize jackknife+ predictive bands around sorted predictions and see where actuals fall outside the interval.",
    "dataviz.regression.uncertainty.quantile_calibration_plot_static": "Use to check whether predicted quantiles are calibrated by plotting nominal vs empirical coverage against the ideal diagonal.",
    "dataviz.regression.uncertainty.quantile_calibration_plot_interactive": "Use to check whether predicted quantiles are calibrated by plotting nominal vs empirical coverage against the ideal diagonal.",
    "dataviz.regression.uncertainty.sharpness_vs_coverage_plot_static": "Compare models on the interval-width vs coverage trade-off to find the one with the sharpest intervals that still cover the target rate.",
    "dataviz.regression.uncertainty.sharpness_vs_coverage_plot_interactive": "Compare models on the interval-width vs coverage trade-off to find the one with the sharpest intervals that still cover the target rate.",
    "dataviz.regression.uncertainty.coverage_by_segment_bar_static": "Use to detect coverage gaps across data segments; bars below the nominal line show subgroups where intervals under-cover.",
    "dataviz.regression.uncertainty.coverage_by_segment_bar_interactive": "Use to detect coverage gaps across data segments; bars below the nominal line show subgroups where intervals under-cover.",
    # validation
    "dataviz.regression.validation.validation_curve_static": "Use to tune a hyperparameter by plotting train and validation scores against its values; widening gaps signal overfitting.",
    "dataviz.regression.validation.validation_curve_interactive": "Use to tune a hyperparameter by plotting train and validation scores against its values; widening gaps signal overfitting.",
    "dataviz.regression.validation.training_history_static": "Use to monitor training by plotting per-epoch metric curves such as loss and val_loss to spot divergence, plateaus, or overfitting.",
    "dataviz.regression.validation.training_history_interactive": "Use to monitor training by plotting per-epoch metric curves such as loss and val_loss to spot divergence, plateaus, or overfitting.",
    "dataviz.regression.validation.cv_score_plot_static": "Use to judge model stability by inspecting per-fold cross-validation scores against their mean; high variance across folds warns of sensitivity.",
    "dataviz.regression.validation.cv_score_plot_interactive": "Use to judge model stability by inspecting per-fold cross-validation scores against their mean; high variance across folds warns of sensitivity.",
    "dataviz.regression.validation.bias_variance_plot_static": "Use to visualize the bias-variance trade-off across model complexity and locate the complexity that minimizes total error.",
    "dataviz.regression.validation.bias_variance_plot_interactive": "Use to visualize the bias-variance trade-off across model complexity and locate the complexity that minimizes total error.",
    # var_engineering
    "dataviz.regression.var_engineering.target_vs_feature_smooth_grid_static": "Use in early EDA to screen many features at once via smoothed E[y|x] curves and spot which predictors have nonlinear target relationships.",
    "dataviz.regression.var_engineering.target_vs_feature_smooth_grid_interactive": "Use in early EDA to screen many features at once via smoothed E[y|x] curves and spot which predictors have nonlinear target relationships.",
    "dataviz.regression.var_engineering.feature_target_correlation_bar_static": "Use to rank features by Pearson correlation with the target, sorted by magnitude, as a quick univariate screen before modeling.",
    "dataviz.regression.var_engineering.feature_target_correlation_bar_interactive": "Use to rank features by Pearson correlation with the target, sorted by magnitude, as a quick univariate screen before modeling.",
    "dataviz.regression.var_engineering.target_encoding_curve_static": "Use to sanity-check target encoding by plotting category mean target vs sample size; small-n categories far from the prior are unreliable.",
    "dataviz.regression.var_engineering.target_encoding_curve_interactive": "Use to sanity-check target encoding by plotting category mean target vs sample size; small-n categories far from the prior are unreliable.",
}
