"""Curated use cases for regression member pages."""

USE_CASES = {
    # forecast
    "dataviz.regression.forecast.forecast_vs_actual_static": "Use to overlay actual and forecast series and spot systematic over- or under-prediction over time.",
    "dataviz.regression.forecast.forecast_vs_actual_interactive": "Use to overlay actual and forecast series and spot systematic over- or under-prediction over time.",
    "dataviz.regression.forecast.forecast_error_over_horizon_static": "Use to see how an error metric such as MAE or RMSE grows as the forecast horizon lengthens.",
    "dataviz.regression.forecast.forecast_error_over_horizon_interactive": "Use to see how an error metric such as MAE or RMSE grows as the forecast horizon lengthens.",
    "dataviz.regression.forecast.rolling_forecast_origin_static": "Use to check forecast stability by plotting scores across rolling forecast origins.",
    "dataviz.regression.forecast.rolling_forecast_origin_interactive": "Use to check forecast stability by plotting scores across rolling forecast origins.",
    "dataviz.regression.forecast.backtest_error_distribution_static": "Use to inspect the distribution of backtest errors for bias, skew, and heavy tails.",
    "dataviz.regression.forecast.backtest_error_distribution_interactive": "Use to inspect the distribution of backtest errors for bias, skew, and heavy tails.",
    "dataviz.regression.forecast.expanding_window_metric_curve_static": "Use to see whether forecast accuracy improves as the training window expands.",
    "dataviz.regression.forecast.expanding_window_metric_curve_interactive": "Use to see whether forecast accuracy improves as the training window expands.",
    "dataviz.regression.forecast.forecast_band_plot_static": "Use to show the forecast path with its prediction band and check how often actuals fall inside it.",
    "dataviz.regression.forecast.forecast_band_plot_interactive": "Use to show the forecast path with its prediction band and check how often actuals fall inside it.",
    # glm
    "dataviz.regression.glm.link_function_plot_static": "Use to check the GLM link choice by comparing the linear predictor against the (optionally binned) response.",
    "dataviz.regression.glm.link_function_plot_interactive": "Use to check the GLM link choice by comparing the linear predictor against the (optionally binned) response.",
    "dataviz.regression.glm.deviance_residual_plot_static": "Use to plot deviance residuals against fitted values to detect lack of fit in a GLM.",
    "dataviz.regression.glm.deviance_residual_plot_interactive": "Use to plot deviance residuals against fitted values to detect lack of fit in a GLM.",
    "dataviz.regression.glm.pearson_residual_plot_static": "Use to plot Pearson residuals against fitted means to check the assumed variance structure.",
    "dataviz.regression.glm.pearson_residual_plot_interactive": "Use to plot Pearson residuals against fitted means to check the assumed variance structure.",
    "dataviz.regression.glm.working_residual_plot_static": "Use to plot working residuals against the linear predictor when diagnosing the IRLS fit.",
    "dataviz.regression.glm.working_residual_plot_interactive": "Use to plot working residuals against the linear predictor when diagnosing the IRLS fit.",
    "dataviz.regression.glm.variance_function_plot_static": "Use to visualize the mean-variance relationship V(mu) implied by the chosen GLM family.",
    "dataviz.regression.glm.variance_function_plot_interactive": "Use to visualize the mean-variance relationship V(mu) implied by the chosen GLM family.",
    "dataviz.regression.glm.glm_diagnostic_panel_static": "Use to review deviance, Pearson, working, and link diagnostics for a GLM in one panel.",
    "dataviz.regression.glm.glm_diagnostic_panel_interactive": "Use to review deviance, Pearson, working, and link diagnostics for a GLM in one panel.",
    # gof
    "dataviz.regression.gof.normality_test_panel_static": "Use to assess residual normality with a histogram, Q-Q plot, and Jarque-Bera annotation in one view.",
    "dataviz.regression.gof.normality_test_panel_interactive": "Use to assess residual normality with a histogram, Q-Q plot, and Jarque-Bera annotation in one view.",
    "dataviz.regression.gof.breusch_pagan_plot_static": "Use to check heteroscedasticity by plotting squared residuals against fitted values with the BP statistic.",
    "dataviz.regression.gof.breusch_pagan_plot_interactive": "Use to check heteroscedasticity by plotting squared residuals against fitted values with the BP statistic.",
    "dataviz.regression.gof.white_test_plot_static": "Use to screen for heteroscedasticity with the White test across predictors without assuming a specific form.",
    "dataviz.regression.gof.white_test_plot_interactive": "Use to screen for heteroscedasticity with the White test across predictors without assuming a specific form.",
    "dataviz.regression.gof.durbin_watson_gauge_static": "Use to read the Durbin-Watson statistic on a 0-4 gauge when checking residuals for autocorrelation.",
    "dataviz.regression.gof.durbin_watson_gauge_interactive": "Use to read the Durbin-Watson statistic on a 0-4 gauge when checking residuals for autocorrelation.",
    "dataviz.regression.gof.ljung_box_plot_static": "Use to plot Ljung-Box p-values across lags to detect residual autocorrelation after fitting.",
    "dataviz.regression.gof.ljung_box_plot_interactive": "Use to plot Ljung-Box p-values across lags to detect residual autocorrelation after fitting.",
    "dataviz.regression.gof.residual_dependence_test_panel_static": "Use to review BP, White, Durbin-Watson, and Ljung-Box residual-dependence checks in one panel.",
    "dataviz.regression.gof.residual_dependence_test_panel_interactive": "Use to review BP, White, Durbin-Watson, and Ljung-Box residual-dependence checks in one panel.",
    # helpers
    "dataviz.regression.helpers.RegressionMetrics": "Returned by compute_regression_metrics; carries the summary metrics (e.g., MAE, RMSE, R2) for a regression prediction.",
    "dataviz.regression.helpers.compute_regression_metrics": "Use to compute standard regression metrics from y_true and y_pred without external dependencies.",
    "dataviz.regression.helpers.InfluenceStatistics": "Returned by influence_statistics; carries per-observation leverage, Cook's distance, DFFITS, and DFBETAS.",
    "dataviz.regression.helpers.influence_statistics": "Use to compute leverage, Cook's distance, DFFITS, and DFBETAS when screening OLS fits for influential points.",
    "dataviz.regression.helpers.prediction_intervals": "Use to build symmetric prediction intervals around point predictions at a chosen confidence level.",
    "dataviz.regression.helpers.coefficient_table": "Use to fit OLS and get coefficients with standard errors, t-statistics, and 95% confidence intervals.",
    "dataviz.regression.helpers.autocorrelation": "Use to compute the sample autocorrelation function when checking residuals for serial correlation.",
    "dataviz.regression.helpers.partial_autocorrelation": "Use to compute partial autocorrelations via Durbin-Levinson when identifying lag structure in residuals.",
    "dataviz.regression.helpers.runs_test_signs": "Use to get run counts of residual signs when testing residuals for randomness.",
    "dataviz.regression.helpers.variance_inflation_factors": "Use to compute one VIF per predictor column when screening a design matrix for multicollinearity.",
    "dataviz.regression.helpers.breusch_pagan_statistic": "Use to compute the Breusch-Pagan LM statistic when testing residuals for heteroscedasticity.",
    "dataviz.regression.helpers.white_test_statistic": "Use to compute the White test statistic when checking heteroscedasticity without assuming its form.",
    "dataviz.regression.helpers.ljung_box_statistic": "Use to compute the Ljung-Box Q statistic and p-value when testing residuals for autocorrelation.",
    "dataviz.regression.helpers.jarque_bera_statistic": "Use to compute the Jarque-Bera statistic and p-value when testing residuals for normality.",
    "dataviz.regression.helpers.durbin_watson_statistic": "Use to compute the Durbin-Watson statistic when checking residuals for first-order autocorrelation.",
    "dataviz.regression.helpers.box_cox_loglikelihood": "Use to compute the Box-Cox profile log-likelihood across lambdas when choosing a response transform.",
    "dataviz.regression.helpers.yeo_johnson_loglikelihood": "Use to compute the Yeo-Johnson profile log-likelihood when transforming responses that include negatives.",
    "dataviz.regression.helpers.conformal_quantile": "Use to get the split-conformal quantile of absolute residuals for distribution-free interval calibration.",
    "dataviz.regression.helpers.jackknife_plus_intervals": "Use to build Jackknife+ prediction intervals when you need coverage guarantees without distribution assumptions.",
    # importance
    "dataviz.regression.importance.feature_importance_regression_static": "Use to rank regression features by the model's built-in importance scores in a descending bar chart.",
    "dataviz.regression.importance.feature_importance_regression_interactive": "Use to rank regression features by the model's built-in importance scores in a descending bar chart.",
    "dataviz.regression.importance.permutation_importance_regression_static": "Use to measure feature impact by permutation with mean and standard-deviation error bars.",
    "dataviz.regression.importance.permutation_importance_regression_interactive": "Use to measure feature impact by permutation with mean and standard-deviation error bars.",
    # influence
    "dataviz.regression.influence.leverage_plot_static": "Use to flag high-leverage observations against the 2p/n threshold before refitting a model.",
    "dataviz.regression.influence.leverage_plot_interactive": "Use to flag high-leverage observations against the 2p/n threshold before refitting a model.",
    "dataviz.regression.influence.cooks_distance_plot_static": "Use to flag influential observations whose removal would shift the fit, using a 4/n threshold.",
    "dataviz.regression.influence.cooks_distance_plot_interactive": "Use to flag influential observations whose removal would shift the fit, using a 4/n threshold.",
    "dataviz.regression.influence.influence_bubble_plot_static": "Use to view leverage and studentized residuals together, with bubble size encoding Cook's distance.",
    "dataviz.regression.influence.influence_bubble_plot_interactive": "Use to view leverage and studentized residuals together, with bubble size encoding Cook's distance.",
    "dataviz.regression.influence.dfbetas_plot_static": "Use to see which observations most change each coefficient via a DFBETAS heatmap.",
    "dataviz.regression.influence.dfbetas_plot_interactive": "Use to see which observations most change each coefficient via a DFBETAS heatmap.",
    # learning
    "dataviz.regression.learning.learning_curve_static": "Use to plot score against training-set size when diagnosing under- or overfitting.",
    "dataviz.regression.learning.learning_curve_interactive": "Use to plot score against training-set size when diagnosing under- or overfitting.",
    # metrics
    "dataviz.regression.metrics.regression_metrics_bar_static": "Use to summarize a single model's regression metrics side by side in a bar chart.",
    "dataviz.regression.metrics.regression_metrics_bar_interactive": "Use to summarize a single model's regression metrics side by side in a bar chart.",
    "dataviz.regression.metrics.metric_comparison_bar_static": "Use to compare regression metrics across multiple models with a grouped bar chart.",
    "dataviz.regression.metrics.metric_comparison_bar_interactive": "Use to compare regression metrics across multiple models with a grouped bar chart.",
    "dataviz.regression.metrics.metric_radar_static": "Use to compare normalized metric profiles of several models at a glance on a radar chart.",
    "dataviz.regression.metrics.metric_radar_interactive": "Use to compare normalized metric profiles of several models at a glance on a radar chart.",
    "dataviz.regression.metrics.per_segment_metrics_heatmap_static": "Use to compare model performance across data segments with a metrics heatmap.",
    "dataviz.regression.metrics.per_segment_metrics_heatmap_interactive": "Use to compare model performance across data segments with a metrics heatmap.",
}
