"""Curated use cases for spc member pages."""

USE_CASES = {
    # attribute.py
    "dataviz.spc.attribute.p_chart_static": "Use when monitoring a supplier's defect rate across lots of varying size to catch special-cause shifts in proportion nonconforming.",
    "dataviz.spc.attribute.p_chart_interactive": "Use when monitoring a supplier's defect rate across lots of varying size to catch special-cause shifts in proportion nonconforming.",
    "dataviz.spc.attribute.np_chart_static": "Use when counting defective units per lot of constant size, such as daily rejected parts from a fixed production batch.",
    "dataviz.spc.attribute.np_chart_interactive": "Use when counting defective units per lot of constant size, such as daily rejected parts from a fixed production batch.",
    "dataviz.spc.attribute.c_chart_static": "Use when counting defects per inspection unit of constant size, such as flaws per painted panel or solder defects per board.",
    "dataviz.spc.attribute.c_chart_interactive": "Use when counting defects per inspection unit of constant size, such as flaws per painted panel or solder defects per board.",
    "dataviz.spc.attribute.u_chart_static": "Use when tracking defects per unit across samples of varying size, such as scratches per square meter of rolled sheet.",
    "dataviz.spc.attribute.u_chart_interactive": "Use when tracking defects per unit across samples of varying size, such as scratches per square meter of rolled sheet.",
    "dataviz.spc.attribute.g_chart_static": "Use when monitoring opportunities or units produced between rare events, such as defects on a high-yield line.",
    "dataviz.spc.attribute.g_chart_interactive": "Use when monitoring opportunities or units produced between rare events, such as defects on a high-yield line.",
    "dataviz.spc.attribute.t_chart_static": "Use when monitoring elapsed time between rare events, such as hours between equipment failures or safety incidents.",
    "dataviz.spc.attribute.t_chart_interactive": "Use when monitoring elapsed time between rare events, such as hours between equipment failures or safety incidents.",
    "dataviz.spc.attribute.laney_p_chart_static": "Use when a p chart shows over-dispersion from large sample sizes; the Laney p' chart adjusts limits so only true special causes signal.",
    "dataviz.spc.attribute.laney_p_chart_interactive": "Use when a p chart shows over-dispersion from large sample sizes; the Laney p' chart adjusts limits so only true special causes signal.",
    "dataviz.spc.attribute.laney_u_chart_static": "Use when a u chart shows over-dispersion from large or varying areas of opportunity; the Laney u' chart widens limits to match actual variation.",
    "dataviz.spc.attribute.laney_u_chart_interactive": "Use when a u chart shows over-dispersion from large or varying areas of opportunity; the Laney u' chart widens limits to match actual variation.",
    # capability.py
    "dataviz.spc.capability.CapabilityStats": "Carries sample size, mean, std, spec limits, Cp/Cpk, and PPM out-of-spec estimates; consumed when reporting whether a process meets customer specifications.",
    "dataviz.spc.capability.capability_summary": "Use to quantify whether a stable process meets specifications by computing Cp, Cpk, and PPM defect estimates against LSL/USL.",
    "dataviz.spc.capability.capability_histogram_static": "Use to show a process histogram against specification limits with a fitted normal curve, for capability reviews with customers or auditors.",
    "dataviz.spc.capability.capability_histogram_interactive": "Use to show a process histogram against specification limits with a fitted normal curve, for capability reviews with customers or auditors.",
    # charts.py
    "dataviz.spc.charts.control_chart": "Use as the default static control chart entry point when plotting process observations against computed control limits.",
    "dataviz.spc.charts.x_range_chart": "Use as the default static entry point for plotting individual values alongside their moving ranges when subgrouping is impractical.",
    # constants.py
    "dataviz.spc.constants.SPCConstants": "Carries the traditional bias-correction constants (A2, D3, D4, d2, and related) for a subgroup size; consumed when computing classic Xbar-R/S limits.",
    "dataviz.spc.constants.get_d2": "Use to look up the d2 constant for a moving-range span when deriving sigma estimates for individuals charts.",
    "dataviz.spc.constants.get_spc_constants": "Use to fetch the full set of control-chart constants for a subgroup size before computing Xbar-R or Xbar-S limits.",
    # control.py
    "dataviz.spc.control.control_chart_static": "Use to plot process observations against computed control limits to judge whether a process is in statistical control.",
    "dataviz.spc.control.control_chart_interactive": "Use to plot process observations against computed control limits to judge whether a process is in statistical control.",
    # dashboard.py
    "dataviz.spc.dashboard.spc_dashboard_static": "Use to review control, range, distribution, and rule-violation panels together for a compact daily process health check.",
    "dataviz.spc.dashboard.spc_dashboard_interactive": "Use to review control, range, distribution, and rule-violation panels together for a compact daily process health check.",
    # diagnostics.py
    "dataviz.spc.diagnostics.run_chart_static": "Use to plot observations in time order against a median reference to spot runs, trends, and shifts before formal control charting.",
    "dataviz.spc.diagnostics.run_chart_interactive": "Use to plot observations in time order against a median reference to spot runs, trends, and shifts before formal control charting.",
    "dataviz.spc.diagnostics.rule_violation_chart_static": "Use to highlight Western Electric or Nelson rule violations on a control chart so operators see exactly where special causes occurred.",
    "dataviz.spc.diagnostics.rule_violation_chart_interactive": "Use to highlight Western Electric or Nelson rule violations on a control chart so operators see exactly where special causes occurred.",
    "dataviz.spc.diagnostics.pareto_chart_static": "Use to rank defect categories by frequency so improvement teams target the vital few causes driving most nonconformances.",
    "dataviz.spc.diagnostics.pareto_chart_interactive": "Use to rank defect categories by frequency so improvement teams target the vital few causes driving most nonconformances.",
    "dataviz.spc.diagnostics.process_distribution_static": "Use to check the shape, center, and sigma spread of process output with a histogram and sigma bands before assuming normality.",
    "dataviz.spc.diagnostics.process_distribution_interactive": "Use to check the shape, center, and sigma spread of process output with a histogram and sigma bands before assuming normality.",
    "dataviz.spc.diagnostics.zone_chart_static": "Use to score points by sigma zone (1, 2, and 3 sigma bands) as a simple alternative to full run-rule control charts.",
    "dataviz.spc.diagnostics.zone_chart_interactive": "Use to score points by sigma zone (1, 2, and 3 sigma bands) as a simple alternative to full run-rule control charts.",
    # multivariate.py
    "dataviz.spc.multivariate.HotellingT2Result": "Carries T-squared scores, center vector, covariance matrix, and the control limit; consumed when charting or summarizing multivariate process stability.",
    "dataviz.spc.multivariate.hotelling_t2_summary": "Use to compute Hotelling T-squared scores when several correlated process variables must be monitored jointly rather than on separate charts.",
    "dataviz.spc.multivariate.hotelling_t2_chart_static": "Use to chart Hotelling T-squared scores against a control limit to detect multivariate shifts in correlated process variables.",
    "dataviz.spc.multivariate.hotelling_t2_chart_interactive": "Use to chart Hotelling T-squared scores against a control limit to detect multivariate shifts in correlated process variables.",
    # rules.py
    "dataviz.spc.rules.ControlLimits": "Carries center line, lower/upper limits, and sigma estimate for a control chart; consumed by charting and rule-detection functions.",
    "dataviz.spc.rules.RuleViolation": "Carries the observation index, value, violated rule name, and a message for one detected violation; consumed when annotating or grouping rule failures.",
    "dataviz.spc.rules.as_numeric_series": "Use to coerce raw array-like process data into a numeric Series before computing limits or detecting rule violations.",
    "dataviz.spc.rules.individuals_limits": "Use to compute individuals chart limits from single observations via the moving-range sigma estimate.",
    "dataviz.spc.rules.moving_ranges": "Use to compute moving ranges between consecutive observations as the basis for individuals and moving-range chart limits.",
    "dataviz.spc.rules.subgroup_matrix": "Use to reshape raw or grouped observations into a subgroup matrix before computing Xbar-R or Xbar-S limits.",
    "dataviz.spc.rules.xbar_r_limits": "Use to compute Xbar and R chart limits for small subgroups, typically size 2 to 10, using the average range.",
    "dataviz.spc.rules.xbar_s_limits": "Use to compute Xbar and S chart limits for larger subgroups where the standard deviation estimates spread better than the range.",
    "dataviz.spc.rules.detect_rule_violations": "Use to flag Western Electric and Nelson rule violations, such as runs and trends, on a series of process observations.",
    "dataviz.spc.rules.violations_by_index": "Use to group detected rule violations by observation index when annotating multiple rules on a single chart point.",
    # variable.py
    "dataviz.spc.variable.moving_range_chart_static": "Use to monitor short-term variation between consecutive individual measurements, companion to an individuals chart.",
    "dataviz.spc.variable.moving_range_chart_interactive": "Use to monitor short-term variation between consecutive individual measurements, companion to an individuals chart.",
    "dataviz.spc.variable.xbar_r_chart_static": "Use when monitoring subgrouped measurements of small size (2-10) to track both process center and within-subgroup spread.",
    "dataviz.spc.variable.xbar_r_chart_interactive": "Use when monitoring subgrouped measurements of small size (2-10) to track both process center and within-subgroup spread.",
    "dataviz.spc.variable.xbar_s_chart_static": "Use when monitoring larger subgroups where the standard deviation tracks within-subgroup spread more precisely than the range.",
    "dataviz.spc.variable.xbar_s_chart_interactive": "Use when monitoring larger subgroups where the standard deviation tracks within-subgroup spread more precisely than the range.",
    "dataviz.spc.variable.ewma_chart_static": "Use to detect small sustained shifts in the process mean earlier than a Shewhart chart by weighting recent observations more heavily.",
    "dataviz.spc.variable.ewma_chart_interactive": "Use to detect small sustained shifts in the process mean earlier than a Shewhart chart by weighting recent observations more heavily.",
    "dataviz.spc.variable.cusum_chart_static": "Use to detect small persistent drifts in the process mean by accumulating deviations from target over time.",
    "dataviz.spc.variable.cusum_chart_interactive": "Use to detect small persistent drifts in the process mean by accumulating deviations from target over time.",
    "dataviz.spc.variable.imr_chart_static": "Use when monitoring individual measurements with no rational subgrouping, pairing the individuals and moving-range views.",
    "dataviz.spc.variable.imr_chart_interactive": "Use when monitoring individual measurements with no rational subgrouping, pairing the individuals and moving-range views.",
    "dataviz.spc.variable.median_chart_static": "Use when monitoring subgrouped measurements by subgroup median, a robust X-tilde alternative when outliers skew the mean.",
    "dataviz.spc.variable.median_chart_interactive": "Use when monitoring subgrouped measurements by subgroup median, a robust X-tilde alternative when outliers skew the mean.",
    "dataviz.spc.variable.levey_jennings_chart_static": "Use in laboratories to monitor assay or instrument QC results against 1, 2, and 3 sigma zones around the mean.",
    "dataviz.spc.variable.levey_jennings_chart_interactive": "Use in laboratories to monitor assay or instrument QC results against 1, 2, and 3 sigma zones around the mean.",
    # x_range.py
    "dataviz.spc.x_range.x_range_chart_static": "Use to plot individual values with their moving ranges for processes measured one part at a time.",
    "dataviz.spc.x_range.x_range_chart_interactive": "Use to plot individual values with their moving ranges for processes measured one part at a time.",
}
