"""Curated use cases for univariate member pages."""

USE_CASES = {
    # inference.py
    "dataviz.univariate.inference.BootstrapCI": "Immutable result carrying the original estimate, percentile bootstrap bounds, confidence level, and resample count; consumed by reports and downstream interval checks.",
    "dataviz.univariate.inference.bootstrap_distribution": "Use to generate resampled values of a mean, median, or std so you can inspect sampling variability without parametric assumptions.",
    "dataviz.univariate.inference.bootstrap_ci": "Use when you need a confidence interval for a mean, median, or std but cannot rely on normality or a closed-form formula.",
    "dataviz.univariate.inference.bootstrap_distribution_plot_static": "Use to visualize the bootstrap distribution of a statistic with the observed estimate marked, to judge stability and skew of the interval.",
    "dataviz.univariate.inference.bootstrap_distribution_plot_interactive": "Use to visualize the bootstrap distribution of a statistic with the observed estimate marked, to judge stability and skew of the interval.",
    # ordinal.py
    "dataviz.univariate.ordinal.ordered_category_counts": "Use to count or normalize ordinal responses in a meaningful category order instead of frequency-sorted order.",
    "dataviz.univariate.ordinal.likert_summary": "Use to tabulate one Likert-scale item with counts, proportions, and cumulative proportions for survey reporting.",
    "dataviz.univariate.ordinal.ordinal_bar_static": "Use to plot ordinal category counts or proportions in a fixed meaningful order, avoiding misleading frequency sorting.",
    "dataviz.univariate.ordinal.ordinal_bar_interactive": "Use to plot ordinal category counts or proportions in a fixed meaningful order, avoiding misleading frequency sorting.",
    # profile.py
    "dataviz.univariate.profile.UnivariateProfile": "Immutable result carrying the variable name, inferred kind, data quality summary, and a type-specific summary payload from auto_profile.",
    "dataviz.univariate.profile.auto_profile": "Use to get a type-aware first-pass profile of one variable, including quality metrics and kind-appropriate summary statistics.",
    "dataviz.univariate.profile.auto_profile_chart_interactive": "Use when you want one sensible interactive chart chosen automatically from the inferred variable type.",
    # quality.py
    "dataviz.univariate.quality.DataQualitySummary": "Immutable record of count, missingness, uniqueness, duplicate, zero, and negative rates; consumed as a quick screening profile for one variable.",
    "dataviz.univariate.quality.data_quality_summary": "Use as a first-pass screen of one variable for missingness, duplicates, zeros, and negatives before choosing downstream visualizations.",
    "dataviz.univariate.quality.quality_bar_static": "Use to compare missing, duplicate, zero, and negative rates side by side when triaging data quality issues.",
    "dataviz.univariate.quality.quality_bar_interactive": "Use to compare missing, duplicate, zero, and negative rates side by side when triaging data quality issues.",
    "dataviz.univariate.quality.sentinel_value_counts": "Use to count configured placeholder values such as -999 or N/A that encode missingness without being null.",
    "dataviz.univariate.quality.sentinel_rate": "Use to quantify how much of a variable is made of sentinel placeholders so you can decide on recoding.",
    # robust.py
    "dataviz.univariate.robust.RobustStats": "Immutable record of median, MAD, scaled MAD, trimmed and winsorized means, quartiles, IQR, and Tukey fences for one numeric variable.",
    "dataviz.univariate.robust.validate_proportion": "Use to validate a trim or winsorize tail proportion is in [0, 0.5) before calling robust helpers.",
    "dataviz.univariate.robust.mad_zscores": "Use to score points by distance from the median in MAD units when mean and standard deviation are distorted by extremes.",
    "dataviz.univariate.robust.mad_outliers": "Use to flag outliers with a robust MAD-based rule on heavy-tailed data where z-scores break down.",
    "dataviz.univariate.robust.trimmed_mean": "Use to estimate central tendency after dropping a fraction of each tail, reducing the influence of extreme values.",
    "dataviz.univariate.robust.winsorize_series": "Use to clip both tails to quantile bounds while preserving sample size, softening extreme values before modeling.",
    "dataviz.univariate.robust.robust_summary": "Use to get center, spread, and fence statistics that resist heavy tails and isolated extreme observations.",
    "dataviz.univariate.robust.robust_location_plot_static": "Use to see where the median, trimmed mean, and winsorized mean fall on the histogram and spot disagreement between centers.",
    "dataviz.univariate.robust.robust_location_plot_interactive": "Use to see where the median, trimmed mean, and winsorized mean fall on the histogram and spot disagreement between centers.",
    # stats.py
    "dataviz.univariate.stats.UnivariateStats": "Immutable record of count, center, spread, shape, and robust spread statistics returned by univariate_summary; convertible with dataclasses.asdict.",
    "dataviz.univariate.stats.as_numeric_series": "Use to coerce series-like input into a clean non-missing numeric Series before computing univariate statistics.",
    "dataviz.univariate.stats.univariate_summary": "Use for a complete descriptive summary of one numeric variable, including quartiles, skewness, kurtosis, SEM, and MAD.",
    "dataviz.univariate.stats.iqr_outliers": "Use to flag observations outside Tukey IQR fences for classic box-plot-style outlier detection.",
    "dataviz.univariate.stats.zscore_outliers": "Use to flag observations whose absolute z-score exceeds a threshold on roughly symmetric, light-tailed data.",
    "dataviz.univariate.stats.recommended_bin_count": "Use to pick a defensible histogram bin count from Freedman-Diaconis, Sturges, Rice, or square-root rules.",
    "dataviz.univariate.stats.percentile_table": "Use to build a percentile-versus-value table for distribution reporting or threshold selection.",
    # tail.py
    "dataviz.univariate.tail.ConcentrationStats": "Immutable record of total, Gini coefficient, and top-10/top-20 shares summarizing inequality in non-negative values.",
    "dataviz.univariate.tail.survival_values": "Use to get sorted values and empirical survival probabilities (1 - ECDF) for custom upper-tail plots or calculations.",
    "dataviz.univariate.tail.exceedance_table": "Use to tabulate how often values exceed candidate thresholds, for example SLA breaches or regulatory limits.",
    "dataviz.univariate.tail.concentration_summary": "Use to quantify inequality or concentration with Gini and top-share metrics for revenue, income, or claim amounts.",
    "dataviz.univariate.tail.lorenz_curve_values": "Use to get cumulative population and value share coordinates for custom Lorenz curve rendering.",
    "dataviz.univariate.tail.survival_curve_static": "Use to emphasize upper-tail behavior by plotting the probability of exceeding each value instead of a density.",
    "dataviz.univariate.tail.survival_curve_interactive": "Use to emphasize upper-tail behavior by plotting the probability of exceeding each value instead of a density.",
    "dataviz.univariate.tail.lorenz_curve_static": "Use to visualize inequality in non-negative values against the perfect-equality reference line.",
    "dataviz.univariate.tail.lorenz_curve_interactive": "Use to visualize inequality in non-negative values against the perfect-equality reference line.",
    # text.py
    "dataviz.univariate.text.BooleanSummary": "Immutable record of true/false counts and the true rate for one boolean indicator variable.",
    "dataviz.univariate.text.BooleanRateInterval": "Immutable record of an observed true rate with Wilson confidence bounds; consumed when reporting binary proportions.",
    "dataviz.univariate.text.boolean_summary": "Use to summarize a binary flag with true/false counts and the true rate.",
    "dataviz.univariate.text.boolean_wilson_interval": "Use to attach a Wilson confidence interval to a boolean rate, which behaves better than Wald near 0 or 1.",
    "dataviz.univariate.text.string_length_summary": "Use to profile text fields by character length, for example to spot truncation or outlier records.",
    "dataviz.univariate.text.token_count_summary": "Use to profile text fields by whitespace token count, for example message or description verbosity.",
    "dataviz.univariate.text.top_terms": "Use to list the most frequent whitespace-delimited terms for lightweight text profiling without NLP dependencies.",
    "dataviz.univariate.text.boolean_bar_static": "Use to plot true/false counts for a binary indicator as a semantic wrapper around categorical frequency bars.",
    "dataviz.univariate.text.boolean_bar_interactive": "Use to plot true/false counts for a binary indicator as a semantic wrapper around categorical frequency bars.",
    "dataviz.univariate.text.top_terms_bar_static": "Use to chart the most common terms in a text column for quick exploratory profiling.",
    "dataviz.univariate.text.top_terms_bar_interactive": "Use to chart the most common terms in a text column for quick exploratory profiling.",
    # transforms.py
    "dataviz.univariate.transforms.TransformResult": "Immutable record of transformed values, method name, and fitted parameter (for Box-Cox or Yeo-Johnson) returned by transform_series.",
    "dataviz.univariate.transforms.transform_series": "Use to apply log, sqrt, Box-Cox, or Yeo-Johnson transformations to tame skew before analysis or modeling.",
    "dataviz.univariate.transforms.transformation_summary": "Use to compare skewness, kurtosis, and spread across candidate transformations and pick the most normalizing one.",
    "dataviz.univariate.transforms.transformation_comparison_static": "Use to compare histograms of common transformations side by side when deciding how to handle skewed data.",
    "dataviz.univariate.transforms.transformation_comparison_interactive": "Use to compare histograms of common transformations side by side when deciding how to handle skewed data.",
    # treatment.py
    "dataviz.univariate.treatment.OutlierTreatmentResult": "Immutable record of original values, treated values, outlier mask, method, and rule, preserving both series for auditability.",
    "dataviz.univariate.treatment.outlier_mask": "Use to get a boolean outlier mask from a named rule (iqr, zscore, or mad) as a shared input to treatment workflows.",
    "dataviz.univariate.treatment.cap_outliers": "Use to clip outliers to the non-outlier range while preserving sample size.",
    "dataviz.univariate.treatment.remove_outliers": "Use to drop flagged outliers when shrinking the sample is acceptable for the analysis.",
    "dataviz.univariate.treatment.flag_outliers": "Use to keep all values but add an explicit is_outlier column when downstream users need transparency.",
    "dataviz.univariate.treatment.outlier_treatment_comparison_static": "Use to review original versus capped or removed distributions side by side before approving a treatment.",
    "dataviz.univariate.treatment.outlier_treatment_comparison_interactive": "Use to review original versus capped or removed distributions side by side before approving a treatment.",
    # violin_plot.py
    "dataviz.univariate.violin_plot.violin_plot_static": "Use to show the full distribution shape with density width plus an inner box, revealing modality that a box plot hides.",
    "dataviz.univariate.violin_plot.violin_plot_interactive": "Use to show the full distribution shape with density width plus an inner box, revealing modality that a box plot hides.",
    # weighted.py
    "dataviz.univariate.weighted.WeightedStats": "Immutable record of weighted count, weight sum, mean, population variance, std, and quartiles for survey or grouped data.",
    "dataviz.univariate.weighted.resolve_weighted_series": "Use to align and validate values with non-negative weights, dropping incomplete rows, before weighted computations.",
    "dataviz.univariate.weighted.weighted_quantile": "Use to compute quantiles that respect per-observation weights, for example a weighted median of survey responses.",
    "dataviz.univariate.weighted.weighted_summary": "Use to summarize survey, grouped, or importance-weighted data with weighted center, spread, and quartiles.",
    "dataviz.univariate.weighted.weighted_histogram_static": "Use to plot a histogram where rows carry unequal sample mass, such as weighted survey records.",
    "dataviz.univariate.weighted.weighted_histogram_interactive": "Use to plot a histogram where rows carry unequal sample mass, such as weighted survey records.",
    "dataviz.univariate.weighted.weighted_ecdf_values": "Use to get sorted values and weight-normalized cumulative probabilities for custom weighted ECDF rendering.",
    "dataviz.univariate.weighted.weighted_ecdf_plot_static": "Use to plot the empirical cumulative distribution when observations contribute unequal weight.",
    "dataviz.univariate.weighted.weighted_ecdf_plot_interactive": "Use to plot the empirical cumulative distribution when observations contribute unequal weight.",
}
