"""Curated use cases for xai member pages."""

USE_CASES = {
    # importance_more
    "dataviz.xai.importance_more.gain_importance_bar_static": "Use to rank features by gradient-boosting gain, optionally overlaying split counts on a second axis to spot overused weak splits.",
    "dataviz.xai.importance_more.gain_importance_bar_interactive": "Use to rank features by gradient-boosting gain, optionally overlaying split counts on a second axis to spot overused weak splits.",
    "dataviz.xai.importance_more.importance_stability_plot_static": "Use to check whether feature rankings are stable across CV folds or seeds; wide error bars flag unreliable importances.",
    "dataviz.xai.importance_more.importance_stability_plot_interactive": "Use to check whether feature rankings are stable across CV folds or seeds; wide error bars flag unreliable importances.",
    "dataviz.xai.importance_more.importance_correlation_heatmap_static": "Use to verify that different models agree on which features matter by correlating their importance vectors.",
    "dataviz.xai.importance_more.importance_correlation_heatmap_interactive": "Use to verify that different models agree on which features matter by correlating their importance vectors.",
    "dataviz.xai.importance_more.feature_clustermap_static": "Use to group features that share an importance signature across models or folds, revealing redundant or cohort-specific signals.",
    "dataviz.xai.importance_more.feature_clustermap_interactive": "Use to group features that share an importance signature across models or folds, revealing redundant or cohort-specific signals.",
    # local_explanations
    "dataviz.xai.local_explanations.shap_force_plot_static": "Use to explain one prediction as a horizontal push-pull of features from the base value to f(x), ideal for single-case narratives.",
    "dataviz.xai.local_explanations.shap_force_plot_interactive": "Use to explain one prediction as a horizontal push-pull of features from the base value to f(x), ideal for single-case narratives.",
    "dataviz.xai.local_explanations.shap_decision_plot_static": "Use to trace cumulative SHAP paths from base to prediction for many instances at once, exposing typical and atypical decision routes.",
    "dataviz.xai.local_explanations.shap_decision_plot_interactive": "Use to trace cumulative SHAP paths from base to prediction for many instances at once, exposing typical and atypical decision routes.",
    "dataviz.xai.local_explanations.lime_explanation_bar_static": "Use to show a LIME-style signed bar of which feature conditions raised or lowered one instance's prediction.",
    "dataviz.xai.local_explanations.lime_explanation_bar_interactive": "Use to show a LIME-style signed bar of which feature conditions raised or lowered one instance's prediction.",
    # local_more
    "dataviz.xai.local_more.anchor_explanation_plot_static": "Use to present anchor rules with precision and coverage side by side, showing how reliable and how broad each if-then rule is.",
    "dataviz.xai.local_more.anchor_explanation_plot_interactive": "Use to present anchor rules with precision and coverage side by side, showing how reliable and how broad each if-then rule is.",
    "dataviz.xai.local_more.nearest_neighbor_explanation_static": "Use to justify a prediction by comparing the query row's feature values against its k nearest neighbors in a heatmap.",
    "dataviz.xai.local_more.nearest_neighbor_explanation_interactive": "Use to justify a prediction by comparing the query row's feature values against its k nearest neighbors in a heatmap.",
    "dataviz.xai.local_more.prototype_criticism_grid_static": "Use to contrast representative prototypes with atypical criticisms side by side, summarizing what is typical and what the model may mishandle.",
    "dataviz.xai.local_more.prototype_criticism_grid_interactive": "Use to contrast representative prototypes with atypical criticisms side by side, summarizing what is typical and what the model may mishandle.",
    "dataviz.xai.local_more.contrastive_explanation_bar_static": "Use to show why a prediction holds (pertinent positives) versus what minimal changes would flip it (pertinent negatives).",
    "dataviz.xai.local_more.contrastive_explanation_bar_interactive": "Use to show why a prediction holds (pertinent positives) versus what minimal changes would flip it (pertinent negatives).",
    # partial_dep
    "dataviz.xai.partial_dep.partial_dependence_static": "Use to show the average marginal effect of one feature on predictions, with optional confidence band and rug marks for data density.",
    "dataviz.xai.partial_dep.partial_dependence_interactive": "Use to show the average marginal effect of one feature on predictions, with optional confidence band and rug marks for data density.",
    # pdp_extra
    "dataviz.xai.pdp_extra.partial_dependence_2d_heatmap_static": "Use to inspect pairwise feature interactions on a precomputed 2-D partial dependence grid.",
    "dataviz.xai.pdp_extra.partial_dependence_2d_heatmap_interactive": "Use to inspect pairwise feature interactions on a precomputed 2-D partial dependence grid.",
    "dataviz.xai.pdp_extra.ice_plot_static": "Use to reveal heterogeneous effects hidden by PDP: each ICE curve shows one instance's response as a feature sweeps its range.",
    "dataviz.xai.pdp_extra.ice_plot_interactive": "Use to reveal heterogeneous effects hidden by PDP: each ICE curve shows one instance's response as a feature sweeps its range.",
    "dataviz.xai.pdp_extra.centered_ice_plot_static": "Use to compare ICE curves anchored at zero at the left endpoint, making differences in slope and shape easier to read than raw levels.",
    "dataviz.xai.pdp_extra.centered_ice_plot_interactive": "Use to compare ICE curves anchored at zero at the left endpoint, making differences in slope and shape easier to read than raw levels.",
    "dataviz.xai.pdp_extra.ale_plot_1d_static": "Use instead of PDP when features are correlated; ALE accumulates local effects within data-supported bins to avoid extrapolation bias.",
    "dataviz.xai.pdp_extra.ale_plot_1d_interactive": "Use instead of PDP when features are correlated; ALE accumulates local effects within data-supported bins to avoid extrapolation bias.",
    # shap
    "dataviz.xai.shap.shap_plot_static": "Use to rank features by mean signed SHAP value with direction-coded bars, a quick global read on which features push predictions up or down.",
    "dataviz.xai.shap.shap_plot_interactive": "Use to rank features by mean signed SHAP value with direction-coded bars, a quick global read on which features push predictions up or down.",
    # shap_extra
    "dataviz.xai.shap_extra.shap_summary_dot_static": "Use as the canonical SHAP beeswarm: per-instance SHAP values per feature, colored by feature value to expose direction and spread.",
    "dataviz.xai.shap_extra.shap_summary_dot_interactive": "Use as the canonical SHAP beeswarm: per-instance SHAP values per feature, colored by feature value to expose direction and spread.",
    "dataviz.xai.shap_extra.shap_bar_global_static": "Use to rank features by mean absolute SHAP when only magnitude of impact matters, not direction.",
    "dataviz.xai.shap_extra.shap_bar_global_interactive": "Use to rank features by mean absolute SHAP when only magnitude of impact matters, not direction.",
    "dataviz.xai.shap_extra.shap_violin_static": "Use to compare the full distribution of SHAP values per feature, revealing skew and outliers that bars hide.",
    "dataviz.xai.shap_extra.shap_violin_interactive": "Use to compare the full distribution of SHAP values per feature, revealing skew and outliers that bars hide.",
    "dataviz.xai.shap_extra.shap_dependence_plot_static": "Use to see how one feature's SHAP value varies with its raw value, optionally colored by a second feature to surface interactions.",
    "dataviz.xai.shap_extra.shap_dependence_plot_interactive": "Use to see how one feature's SHAP value varies with its raw value, optionally colored by a second feature to surface interactions.",
    "dataviz.xai.shap_extra.shap_interaction_heatmap_static": "Use to find which feature pairs carry the strongest SHAP interaction effects before drilling into dependence plots.",
    "dataviz.xai.shap_extra.shap_interaction_heatmap_interactive": "Use to find which feature pairs carry the strongest SHAP interaction effects before drilling into dependence plots.",
    "dataviz.xai.shap_extra.shap_waterfall_plot_static": "Use to walk one prediction from base value to f(x) feature by feature; small contributions collapse into an 'other' bar via top_n.",
    "dataviz.xai.shap_extra.shap_waterfall_plot_interactive": "Use to walk one prediction from base value to f(x) feature by feature; small contributions collapse into an 'other' bar via top_n.",
    # shap_more
    "dataviz.xai.shap_more.shap_beeswarm_plot_static": "Use as a density-jittered SHAP beeswarm colored by feature value; tighter packing than the dot summary for large datasets.",
    "dataviz.xai.shap_more.shap_beeswarm_plot_interactive": "Use as a density-jittered SHAP beeswarm colored by feature value; tighter packing than the dot summary for large datasets.",
    "dataviz.xai.shap_more.shap_heatmap_instances_static": "Use to spot clusters of similarly explained instances by plotting the SHAP matrix sorted by instance similarity.",
    "dataviz.xai.shap_more.shap_heatmap_instances_interactive": "Use to spot clusters of similarly explained instances by plotting the SHAP matrix sorted by instance similarity.",
    "dataviz.xai.shap_more.shap_force_stacked_static": "Use to visualize how each feature's contributions stack up across many instances relative to the base value.",
    "dataviz.xai.shap_more.shap_force_stacked_interactive": "Use to visualize how each feature's contributions stack up across many instances relative to the base value.",
    "dataviz.xai.shap_more.shap_main_vs_interaction_bar_static": "Use to decompose each feature's impact into main effects versus interaction effects, flagging features that only matter in combination.",
    "dataviz.xai.shap_more.shap_main_vs_interaction_bar_interactive": "Use to decompose each feature's impact into main effects versus interaction effects, flagging features that only matter in combination.",
    "dataviz.xai.shap_more.shap_monotonicity_plot_static": "Use to check whether a feature's SHAP values rise monotonically with its value, with an isotonic fit overlay for validation audits.",
    "dataviz.xai.shap_more.shap_monotonicity_plot_interactive": "Use to check whether a feature's SHAP values rise monotonically with its value, with an isotonic fit overlay for validation audits.",
    "dataviz.xai.shap_more.shap_temporal_drift_static": "Use to track mean absolute SHAP per feature over time windows, detecting when the model's driving features drift.",
    "dataviz.xai.shap_more.shap_temporal_drift_interactive": "Use to track mean absolute SHAP per feature over time windows, detecting when the model's driving features drift.",
    # surrogate
    "dataviz.xai.surrogate.surrogate_tree_plot_static": "Use to render a shallow interpretable tree distilled from a black-box model, supplied as a list of depth/condition/prediction rule dicts.",
    "dataviz.xai.surrogate.surrogate_tree_plot_interactive": "Use to render a shallow interpretable tree distilled from a black-box model, supplied as a list of depth/condition/prediction rule dicts.",
    "dataviz.xai.surrogate.counterfactual_change_bar_static": "Use to show the smallest per-feature changes needed to flip a prediction, annotated with original to counterfactual values.",
    "dataviz.xai.surrogate.counterfactual_change_bar_interactive": "Use to show the smallest per-feature changes needed to flip a prediction, annotated with original to counterfactual values.",
    # uncertainty
    "dataviz.xai.uncertainty.prediction_uncertainty_plot_static": "Use to plot predictions against a feature with a plus/minus uncertainty band, locating regions where the model is unsure.",
    "dataviz.xai.uncertainty.prediction_uncertainty_plot_interactive": "Use to plot predictions against a feature with a plus/minus uncertainty band, locating regions where the model is unsure.",
    "dataviz.xai.uncertainty.confidence_attribution_bar_static": "Use to attribute predictive uncertainty to individual features, identifying which inputs drive the model's lack of confidence.",
    "dataviz.xai.uncertainty.confidence_attribution_bar_interactive": "Use to attribute predictive uncertainty to individual features, identifying which inputs drive the model's lack of confidence.",
    "dataviz.xai.uncertainty.epistemic_vs_aleatoric_plot_static": "Use to decompose uncertainty into reducible epistemic (model) and irreducible aleatoric (data) components across bins.",
    "dataviz.xai.uncertainty.epistemic_vs_aleatoric_plot_interactive": "Use to decompose uncertainty into reducible epistemic (model) and irreducible aleatoric (data) components across bins.",
}
