"""Curated use cases for xai member pages."""

USE_CASES = {
    "dataviz.xai.charts.feature_importance": "Use when presenting which features drive a model's predictions to non-technical stakeholders.",
    "dataviz.xai.charts.shap_plot": "Use to explain individual and global predictions with SHAP values during model review or debugging.",
    "dataviz.xai.charts.partial_dependence": "Use to show how one feature affects the predicted outcome on average, holding other features constant.",
    "dataviz.xai.cohort.importance_by_segment_heatmap_static": "Use to compare which features matter across cohorts, e.g. regions or customer tiers, in one annotated heatmap.",
    "dataviz.xai.cohort.importance_by_segment_heatmap_interactive": "Use to compare which features matter across cohorts, e.g. regions or customer tiers, in one annotated heatmap.",
    "dataviz.xai.cohort.shap_cluster_heatmap_static": "Use to discover groups of instances with similar SHAP explanation patterns via clustered heatmap ordering.",
    "dataviz.xai.cohort.shap_cluster_heatmap_interactive": "Use to discover groups of instances with similar SHAP explanation patterns via clustered heatmap ordering.",
    "dataviz.xai.comparison.importance_comparison_heatmap_static": "Use to compare feature importances across several models side by side before selecting a champion model.",
    "dataviz.xai.comparison.importance_comparison_heatmap_interactive": "Use to compare feature importances across several models side by side before selecting a champion model.",
    "dataviz.xai.comparison.shap_model_agreement_scatter_static": "Check whether two models attribute predictions to the same features per instance, quantified by Pearson r.",
    "dataviz.xai.comparison.shap_model_agreement_scatter_interactive": "Check whether two models attribute predictions to the same features per instance, quantified by Pearson r.",
    "dataviz.xai.comparison.rashomon_importance_band_static": "Use when several near-optimal models disagree, to show the min-to-max range of plausible feature importances.",
    "dataviz.xai.comparison.rashomon_importance_band_interactive": "Use when several near-optimal models disagree, to show the min-to-max range of plausible feature importances.",
    "dataviz.xai.concept.concept_activation_bar_static": "Use to test whether human-interpretable concepts influence a neural network, with non-significant concepts greyed out.",
    "dataviz.xai.concept.concept_activation_bar_interactive": "Use to test whether human-interpretable concepts influence a neural network, with non-significant concepts greyed out.",
    "dataviz.xai.concept.saliency_overlay_plot_static": "Use to inspect which image regions drive a vision model by overlaying saliency or Grad-CAM heatmaps on the inputs.",
    "dataviz.xai.concept.saliency_overlay_plot_interactive": "Use to inspect which image regions drive a vision model by overlaying saliency or Grad-CAM heatmaps on the inputs.",
    "dataviz.xai.concept.attention_heatmap_static": "Use to visualize attention weights across tokens or features in transformer-style models during error analysis.",
    "dataviz.xai.concept.attention_heatmap_interactive": "Use to visualize attention weights across tokens or features in transformer-style models during error analysis.",
    "dataviz.xai.concept.embedding_projection_plot_static": "Use to explore a 2-D embedding projection colored by class or feature value to spot clusters and outliers.",
    "dataviz.xai.concept.embedding_projection_plot_interactive": "Use to explore a 2-D embedding projection colored by class or feature value to spot clusters and outliers.",
    "dataviz.xai.counterfactuals.counterfactual_path_plot_static": "Use to show the sequence of feature changes needed to flip a single prediction, e.g. a loan denial.",
    "dataviz.xai.counterfactuals.counterfactual_path_plot_interactive": "Use to show the sequence of feature changes needed to flip a single prediction, e.g. a loan denial.",
    "dataviz.xai.counterfactuals.diverse_counterfactual_grid_static": "Compare several diverse counterfactuals at once to offer users multiple actionable ways to change an outcome.",
    "dataviz.xai.counterfactuals.diverse_counterfactual_grid_interactive": "Compare several diverse counterfactuals at once to offer users multiple actionable ways to change an outcome.",
    "dataviz.xai.counterfactuals.what_if_slider_plot_static": "Use to sweep one feature and watch the predicted outcome change, answering what-if questions for end users.",
    "dataviz.xai.counterfactuals.what_if_slider_plot_interactive": "Use to sweep one feature and watch the predicted outcome change, answering what-if questions for end users.",
    "dataviz.xai.dependence_more.pdp_with_ice_overlay_static": "Use to show the average feature effect while revealing heterogeneous per-instance behavior hidden by a plain PDP.",
    "dataviz.xai.dependence_more.pdp_with_ice_overlay_interactive": "Use to show the average feature effect while revealing heterogeneous per-instance behavior hidden by a plain PDP.",
    "dataviz.xai.dependence_more.ale_plot_2d_static": "Use to visualize the joint effect of two correlated features without the extrapolation bias of 2-D PDPs.",
    "dataviz.xai.dependence_more.ale_plot_2d_interactive": "Use to visualize the joint effect of two correlated features without the extrapolation bias of 2-D PDPs.",
    "dataviz.xai.dependence_more.h_statistic_heatmap_static": "Use to screen for pairwise feature interactions with Friedman's H-statistic before deeper interaction analysis.",
    "dataviz.xai.dependence_more.h_statistic_heatmap_interactive": "Use to screen for pairwise feature interactions with Friedman's H-statistic before deeper interaction analysis.",
    "dataviz.xai.dependence_more.interaction_network_static": "Use to communicate the strongest feature interactions as a network graph for reports or presentations.",
    "dataviz.xai.dependence_more.interaction_network_interactive": "Use to communicate the strongest feature interactions as a network graph for reports or presentations.",
    "dataviz.xai.fairness_xai.disparate_impact_by_segment_static": "Use in fairness audits to see which features drive predictions per segment alongside each segment's outcome rate.",
    "dataviz.xai.fairness_xai.disparate_impact_by_segment_interactive": "Use in fairness audits to see which features drive predictions per segment alongside each segment's outcome rate.",
    "dataviz.xai.fairness_xai.subgroup_shap_divergence_static": "Check whether a model relies on features differently across protected subgroups by comparing SHAP distributions.",
    "dataviz.xai.fairness_xai.subgroup_shap_divergence_interactive": "Check whether a model relies on features differently across protected subgroups by comparing SHAP distributions.",
    "dataviz.xai.fairness_xai.intersectional_importance_heatmap_static": "Use to audit feature importance across intersectional segments, e.g. gender by age group, in one heatmap.",
    "dataviz.xai.fairness_xai.intersectional_importance_heatmap_interactive": "Use to audit feature importance across intersectional segments, e.g. gender by age group, in one heatmap.",
    "dataviz.xai.feature_imp.feature_importance_static": "Use when presenting which features drive a model's predictions to non-technical stakeholders.",
    "dataviz.xai.feature_imp.feature_importance_interactive": "Use when presenting which features drive a model's predictions to non-technical stakeholders.",
    "dataviz.xai.importance_extra.permutation_importance_bar_static": "Use for model-agnostic importance estimates measured by the performance drop when each feature is shuffled.",
    "dataviz.xai.importance_extra.permutation_importance_bar_interactive": "Use for model-agnostic importance estimates measured by the performance drop when each feature is shuffled.",
    "dataviz.xai.importance_extra.feature_importance_grouped_bar_static": "Compare importance rankings across multiple models to confirm key drivers are consistent before deployment.",
    "dataviz.xai.importance_extra.feature_importance_grouped_bar_interactive": "Compare importance rankings across multiple models to confirm key drivers are consistent before deployment.",
    "dataviz.xai.importance_extra.feature_importance_boxplot_static": "Use to assess the stability of importance estimates across CV folds or repeated runs via per-feature spread.",
    "dataviz.xai.importance_extra.feature_importance_boxplot_interactive": "Use to assess the stability of importance estimates across CV folds or repeated runs via per-feature spread.",
    "dataviz.xai.importance_extra.drop_column_importance_bar_static": "Use to measure each feature's contribution by retraining without it; signed values show helpful vs. harmful columns.",
    "dataviz.xai.importance_extra.drop_column_importance_bar_interactive": "Use to measure each feature's contribution by retraining without it; signed values show helpful vs. harmful columns.",
    "dataviz.xai.importance_extra.importance_method_scatter_static": "Check agreement between two importance methods to validate that conclusions do not depend on one technique.",
    "dataviz.xai.importance_extra.importance_method_scatter_interactive": "Check agreement between two importance methods to validate that conclusions do not depend on one technique.",
}
