"""
DataViz - A comprehensive data visualization package.

This package provides easy-to-use tools for creating beautiful visualizations
organized by chart type and analysis category. Each chart has both static
(matplotlib/seaborn) and interactive (plotly) versions.

Usage Examples
--------------

Static (default, matplotlib-based):
    >>> import dataviz as dv
    >>> dv.histogram(data)  # Uses histogram_static
    >>> dv.scatter_plot(x, y)  # Uses scatter_plot_static

Interactive (plotly-based):
    >>> dv.histogram_interactive(data)
    >>> dv.scatter_plot_interactive(x, y)

Or access via submodules:
    >>> dv.univariate.histogram_static(data)
    >>> dv.univariate.histogram_interactive(data)
"""

__version__ = "0.1.0"
__author__ = "PhD Aned Esquerra-Arguelles"
__email__ = "aned.ezquerra@gmail.com"

# Import submodules
from . import spc
from . import univariate
from . import bivariate
from . import multivariate
from . import eda
from . import xai
from . import regression
from . import classification
from . import clustering
from . import utils
from . import types

# Convenience imports - Static versions (default)
from .univariate import (
    histogram_static as histogram,
    density_static as density_plot,
    box_plot_static as box_plot,
    violin_plot_static as violin_plot,
    frequency_bar_static as frequency_bar,
    pareto_chart_static as univariate_pareto_chart,
    ecdf_plot_static as ecdf_plot,
    cumulative_histogram_static as cumulative_histogram,
    qq_plot_static as qq_plot,
    pp_plot_static as pp_plot,
    outlier_plot_static as outlier_plot,
    percentile_plot_static as percentile_plot,
    univariate_diagnostic_panel_static as univariate_diagnostic_panel,
    fitted_distribution_histogram_static as fitted_distribution_histogram,
    robust_location_plot_static as robust_location_plot,
    rug_plot_static as rug_plot,
    strip_plot_static as strip_plot,
    dot_plot_static as dot_plot,
    lollipop_chart_static as lollipop_chart,
    reference_band_histogram_static as reference_band_histogram,
    raincloud_plot_static as raincloud_plot,
    ridgeline_plot_static as ridgeline_plot,
    transformation_comparison_static as transformation_comparison,
    event_frequency_plot_static as event_frequency_plot,
    interarrival_plot_static as interarrival_plot,
    univariate_analysis_dashboard_static as univariate_analysis_dashboard,
    weighted_histogram_static as weighted_histogram,
    quality_bar_static as quality_bar,
    survival_curve_static as survival_curve,
    lorenz_curve_static as lorenz_curve,
    bootstrap_distribution_plot_static as bootstrap_distribution_plot,
    boolean_bar_static as boolean_bar,
    top_terms_bar_static as top_terms_bar,
    weighted_ecdf_plot_static as weighted_ecdf_plot,
    ordinal_bar_static as ordinal_bar,
    outlier_treatment_comparison_static as outlier_treatment_comparison,
    auto_profile_chart_interactive as auto_profile_chart,
    UnivariateInput,
    UnivariateStats,
    RobustStats,
    DistributionFit,
    TransformResult,
    NormalityTestResult,
    WeightedStats,
    DataQualitySummary,
    ConcentrationStats,
    BootstrapCI,
    BooleanSummary,
    BooleanRateInterval,
    OutlierTreatmentResult,
    UnivariateProfile,
    as_datetime_series,
    resolve_weighted_series,
    resolve_univariate_data,
    infer_univariate_kind,
    numeric_or_none,
    category_counts,
    ordered_category_counts,
    ecdf_values,
    survival_values,
    lorenz_curve_values,
    univariate_summary,
    robust_summary,
    weighted_summary,
    data_quality_summary,
    sentinel_value_counts,
    sentinel_rate,
    concentration_summary,
    normality_test,
    fit_distribution,
    compare_distributions,
    fitted_pdf_values,
    transform_series,
    transformation_summary,
    event_counts,
    interarrival_times,
    exceedance_table,
    bootstrap_distribution,
    bootstrap_ci,
    boolean_summary,
    boolean_wilson_interval,
    string_length_summary,
    token_count_summary,
    top_terms,
    likert_summary,
    auto_profile,
    iqr_outliers,
    zscore_outliers,
    mad_outliers,
    mad_zscores,
    trimmed_mean,
    winsorize_series,
    weighted_quantile,
    weighted_ecdf_values,
    outlier_mask,
    cap_outliers,
    remove_outliers,
    flag_outliers,
    recommended_bin_count,
    percentile_table,
)
from .bivariate import (
    scatter_plot_static as scatter_plot,
    line_plot_static as line_plot,
    correlation_heatmap_static as correlation_heatmap,
    bubble_plot_static as bubble_plot,
    hexbin_plot_static as hexbin_plot,
    regression_plot_static as regression_plot,
    density_contour_static as density_contour,
    grouped_bar_static as grouped_bar,
    box_by_category_static as box_by_category,
    violin_by_category_static as violin_by_category,
    crosstab_heatmap_static as crosstab_heatmap,
    binned_mean_plot_static as binned_mean_plot,
    errorbar_plot_static as errorbar_plot,
    area_between_static as area_between,
    step_plot_static as step_plot,
    joint_scatter_hist_static as joint_scatter_hist,
    bivariate_histogram_static as bivariate_histogram,
    BivariateStats,
    bivariate_summary,
    outlier_scatter_static as outlier_scatter,
    residual_relationship_static as residual_relationship,
    quantile_bin_plot_static as quantile_bin_plot,
    bland_altman_static as bland_altman,
    rank_scatter_static as rank_scatter,
    lag_plot_static as lag_plot,
    conditional_box_static as conditional_box,
)
from .eda import (
    missing_data_plot_static as missing_data_plot,
    distribution_summary_static as distribution_summary,
    class_distribution_static as class_distribution,
)
from .regression import (
    residual_plot_static as residual_plot,
    prediction_plot_static as prediction_plot,
    learning_curve_static as learning_curve,
    # Extended regression visualizations exposed at top level
    RegressionMetrics,
    InfluenceStatistics,
    compute_regression_metrics,
    influence_statistics,
    prediction_intervals,
    coefficient_table,
    autocorrelation,
    partial_autocorrelation,
    runs_test_signs,
    compute_regularization_path,
    residual_histogram_static as residual_histogram,
    residual_density_static as residual_density,
    residual_qq_static as residual_qq,
    residual_boxplot_by_group_static as residual_boxplot_by_group,
    standardized_residual_plot_static as standardized_residual_plot,
    scale_location_plot_static as scale_location_plot,
    residual_vs_feature_static as residual_vs_feature,
    partial_residual_plot_static as partial_residual_plot,
    ccpr_plot_static as ccpr_plot,
    added_variable_plot_static as added_variable_plot,
    residual_acf_static as residual_acf,
    residual_pacf_static as residual_pacf,
    residual_runs_plot_static as residual_runs_plot,
    residual_time_plot_static as residual_time_plot,
    pred_vs_actual_hexbin_static as pred_vs_actual_hexbin,
    pred_vs_actual_density_static as pred_vs_actual_density,
    prediction_error_histogram_static as prediction_error_histogram,
    prediction_interval_plot_static as prediction_interval_plot,
    error_by_magnitude_plot_static as error_by_magnitude_plot,
    leverage_plot_static as leverage_plot,
    cooks_distance_plot_static as cooks_distance_plot,
    influence_bubble_plot_static as influence_bubble_plot,
    dfbetas_plot_static as dfbetas_plot,
    coefficient_plot_static as coefficient_plot,
    coefficient_forest_plot_static as coefficient_forest_plot,
    standardized_coefficient_plot_static as standardized_coefficient_plot,
    coefficient_path_plot_static as coefficient_path_plot,
    feature_importance_regression_static as feature_importance_regression,
    permutation_importance_regression_static as permutation_importance_regression,
    lasso_path_static as lasso_path,
    ridge_path_static as ridge_path,
    regularization_validation_plot_static as regularization_validation_plot,
    regression_metrics_bar_static as regression_metrics_bar,
    metric_comparison_bar_static as metric_comparison_bar,
    metric_radar_static as metric_radar,
    per_segment_metrics_heatmap_static as per_segment_metrics_heatmap,
    validation_curve_static as validation_curve,
    training_history_static as training_history,
    cv_score_plot_static as cv_score_plot,
    bias_variance_plot_static as bias_variance_plot,
    calibration_curve_regression_static as calibration_curve_regression,
    prediction_interval_coverage_plot_static as prediction_interval_coverage_plot,
    uncertainty_band_plot_static as uncertainty_band_plot,
    regression_diagnostic_panel_static as regression_diagnostic_panel,
    regression_dashboard_static as regression_dashboard,
    # Batch-2 helpers
    variance_inflation_factors,
    breusch_pagan_statistic,
    white_test_statistic,
    ljung_box_statistic,
    jarque_bera_statistic,
    durbin_watson_statistic,
    box_cox_loglikelihood,
    yeo_johnson_loglikelihood,
    conformal_quantile,
    jackknife_plus_intervals,
    # Batch-2 alias names
    link_function_plot_static as link_function_plot,
    deviance_residual_plot_static as deviance_residual_plot,
    pearson_residual_plot_static as pearson_residual_plot,
    working_residual_plot_static as working_residual_plot,
    variance_function_plot_static as variance_function_plot,
    glm_diagnostic_panel_static as glm_diagnostic_panel,
    quantile_regression_band_static as quantile_regression_band,
    quantile_loss_curve_static as quantile_loss_curve,
    huber_vs_ols_overlay_static as huber_vs_ols_overlay,
    weighted_residual_plot_static as weighted_residual_plot,
    km_predicted_vs_observed_static as km_predicted_vs_observed,
    cox_residual_plot_static as cox_residual_plot,
    proportional_hazards_test_plot_static as proportional_hazards_test_plot,
    forecast_vs_actual_static as forecast_vs_actual,
    forecast_error_over_horizon_static as forecast_error_over_horizon,
    rolling_forecast_origin_static as rolling_forecast_origin,
    backtest_error_distribution_static as backtest_error_distribution,
    expanding_window_metric_curve_static as expanding_window_metric_curve,
    forecast_band_plot_static as forecast_band_plot,
    spatial_residual_map_static as spatial_residual_map,
    moran_scatter_static as moran_scatter,
    panel_residual_heatmap_static as panel_residual_heatmap,
    vif_bar_static as vif_bar,
    condition_index_plot_static as condition_index_plot,
    correlation_heatmap_with_clustering_static as correlation_heatmap_with_clustering,
    eigenvalue_scree_predictors_static as eigenvalue_scree_predictors,
    tolerance_bar_static as tolerance_bar,
    partial_dependence_regression_static as partial_dependence_regression,
    ice_plot_regression_static as ice_plot_regression,
    marginal_effects_plot_static as marginal_effects_plot,
    interaction_effect_plot_static as interaction_effect_plot,
    conditional_expectation_curve_static as conditional_expectation_curve,
    elasticity_plot_static as elasticity_plot,
    normality_test_panel_static as normality_test_panel,
    breusch_pagan_plot_static as breusch_pagan_plot,
    white_test_plot_static as white_test_plot,
    durbin_watson_gauge_static as durbin_watson_gauge,
    ljung_box_plot_static as ljung_box_plot,
    residual_dependence_test_panel_static as residual_dependence_test_panel,
    aic_bic_bar_static as aic_bic_bar,
    nested_model_comparison_plot_static as nested_model_comparison_plot,
    stepwise_selection_path_static as stepwise_selection_path,
    forward_selection_score_curve_static as forward_selection_score_curve,
    best_subset_metric_bar_static as best_subset_metric_bar,
    learning_curve_with_band_static as learning_curve_with_band,
    nested_cv_score_plot_static as nested_cv_score_plot,
    cv_residual_distribution_static as cv_residual_distribution,
    repeated_kfold_violin_static as repeated_kfold_violin,
    group_cv_score_strip_static as group_cv_score_strip,
    conformal_interval_plot_static as conformal_interval_plot,
    jackknife_plus_band_static as jackknife_plus_band,
    quantile_calibration_plot_static as quantile_calibration_plot,
    sharpness_vs_coverage_plot_static as sharpness_vs_coverage_plot,
    coverage_by_segment_bar_static as coverage_by_segment_bar,
    loss_distribution_violin_static as loss_distribution_violin,
    ranked_error_plot_static as ranked_error_plot,
    worst_k_predictions_chart_static as worst_k_predictions_chart,
    error_decomposition_bar_static as error_decomposition_bar,
    random_effect_caterpillar_static as random_effect_caterpillar,
    random_intercept_slope_scatter_static as random_intercept_slope_scatter,
    group_means_vs_predicted_static as group_means_vs_predicted,
    boxcox_likelihood_curve_static as boxcox_likelihood_curve,
    yeojohnson_lambda_search_static as yeojohnson_lambda_search,
    log_log_diagnostic_static as log_log_diagnostic,
    power_transform_residual_panel_static as power_transform_residual_panel,
    target_vs_feature_smooth_grid_static as target_vs_feature_smooth_grid,
    feature_target_correlation_bar_static as feature_target_correlation_bar,
    target_encoding_curve_static as target_encoding_curve,
    posterior_coefficient_density_static as posterior_coefficient_density,
    posterior_predictive_check_static as posterior_predictive_check,
    trace_plot_coefficients_static as trace_plot_coefficients,
    credible_interval_forest_static as credible_interval_forest,
    multi_model_pred_vs_actual_overlay_static as multi_model_pred_vs_actual_overlay,
    residual_density_overlay_multi_static as residual_density_overlay_multi,
    error_ecdf_overlay_static as error_ecdf_overlay,
    model_winner_heatmap_static as model_winner_heatmap,
    price_elasticity_curve_static as price_elasticity_curve,
    dose_response_curve_static as dose_response_curve,
    demand_forecast_fan_chart_static as demand_forecast_fan_chart,
    yield_curve_fit_plot_static as yield_curve_fit_plot,
)
from .classification import (
    confusion_matrix_plot_static as confusion_matrix_plot,
    roc_curve_static as roc_curve,
    precision_recall_curve_static as precision_recall_curve,
)
from .spc import (
    control_chart_static as control_chart,
    x_range_chart_static as x_range_chart,
    moving_range_chart_static as moving_range_chart,
    xbar_r_chart_static as xbar_r_chart,
    xbar_s_chart_static as xbar_s_chart,
    ewma_chart_static as ewma_chart,
    cusum_chart_static as cusum_chart,
    p_chart_static as p_chart,
    np_chart_static as np_chart,
    c_chart_static as c_chart,
    u_chart_static as u_chart,
    capability_histogram_static as capability_histogram,
    ControlLimits,
    RuleViolation,
    SPCConstants,
    SPC_CONSTANTS,
    CapabilityStats,
    HotellingT2Result,
    capability_summary,
    hotelling_t2_summary,
    detect_rule_violations,
    get_spc_constants,
    run_chart_static as run_chart,
    rule_violation_chart_static as rule_violation_chart,
    pareto_chart_static as pareto_chart,
    process_distribution_static as process_distribution,
    zone_chart_static as zone_chart,
    hotelling_t2_chart_static as hotelling_t2_chart,
    spc_dashboard_static as spc_dashboard,
)

# Interactive versions imports
from .univariate import (
    histogram_interactive,
    density_interactive,
    box_plot_interactive,
    violin_plot_interactive,
    frequency_bar_interactive,
    pareto_chart_interactive as univariate_pareto_chart_interactive,
    ecdf_plot_interactive,
    cumulative_histogram_interactive,
    qq_plot_interactive,
    pp_plot_interactive,
    outlier_plot_interactive,
    percentile_plot_interactive,
    univariate_diagnostic_panel_interactive,
    fitted_distribution_histogram_interactive,
    robust_location_plot_interactive,
    rug_plot_interactive,
    strip_plot_interactive,
    dot_plot_interactive,
    lollipop_chart_interactive,
    reference_band_histogram_interactive,
    raincloud_plot_interactive,
    ridgeline_plot_interactive,
    transformation_comparison_interactive,
    event_frequency_plot_interactive,
    interarrival_plot_interactive,
    univariate_analysis_dashboard_interactive,
    weighted_histogram_interactive,
    quality_bar_interactive,
    survival_curve_interactive,
    lorenz_curve_interactive,
    bootstrap_distribution_plot_interactive,
    boolean_bar_interactive,
    top_terms_bar_interactive,
    weighted_ecdf_plot_interactive,
    ordinal_bar_interactive,
    outlier_treatment_comparison_interactive,
    auto_profile_chart_interactive,
)
from .bivariate import (
    scatter_plot_interactive,
    line_plot_interactive,
    correlation_heatmap_interactive,
    bubble_plot_interactive,
    hexbin_plot_interactive,
    regression_plot_interactive,
    density_contour_interactive,
    grouped_bar_interactive,
    box_by_category_interactive,
    violin_by_category_interactive,
    crosstab_heatmap_interactive,
    binned_mean_plot_interactive,
    errorbar_plot_interactive,
    area_between_interactive,
    step_plot_interactive,
    joint_scatter_hist_interactive,
    bivariate_histogram_interactive,
    outlier_scatter_interactive,
    residual_relationship_interactive,
    quantile_bin_plot_interactive,
    bland_altman_interactive,
    rank_scatter_interactive,
    lag_plot_interactive,
    conditional_box_interactive,
)
from .eda import (
    missing_data_plot_interactive,
    distribution_summary_interactive,
    class_distribution_interactive,
)
from .regression import (
    residual_plot_interactive,
    prediction_plot_interactive,
    learning_curve_interactive,
    # Extended interactive variants
    residual_histogram_interactive,
    residual_density_interactive,
    residual_qq_interactive,
    residual_boxplot_by_group_interactive,
    standardized_residual_plot_interactive,
    scale_location_plot_interactive,
    residual_vs_feature_interactive,
    partial_residual_plot_interactive,
    ccpr_plot_interactive,
    added_variable_plot_interactive,
    residual_acf_interactive,
    residual_pacf_interactive,
    residual_runs_plot_interactive,
    residual_time_plot_interactive,
    pred_vs_actual_hexbin_interactive,
    pred_vs_actual_density_interactive,
    prediction_error_histogram_interactive,
    prediction_interval_plot_interactive,
    error_by_magnitude_plot_interactive,
    leverage_plot_interactive,
    cooks_distance_plot_interactive,
    influence_bubble_plot_interactive,
    dfbetas_plot_interactive,
    coefficient_plot_interactive,
    coefficient_forest_plot_interactive,
    standardized_coefficient_plot_interactive,
    coefficient_path_plot_interactive,
    feature_importance_regression_interactive,
    permutation_importance_regression_interactive,
    lasso_path_interactive,
    ridge_path_interactive,
    regularization_validation_plot_interactive,
    regression_metrics_bar_interactive,
    metric_comparison_bar_interactive,
    metric_radar_interactive,
    per_segment_metrics_heatmap_interactive,
    validation_curve_interactive,
    training_history_interactive,
    cv_score_plot_interactive,
    bias_variance_plot_interactive,
    calibration_curve_regression_interactive,
    prediction_interval_coverage_plot_interactive,
    uncertainty_band_plot_interactive,
    regression_diagnostic_panel_interactive,
    regression_dashboard_interactive,
    # Batch-2 interactive variants
    link_function_plot_interactive,
    deviance_residual_plot_interactive,
    pearson_residual_plot_interactive,
    working_residual_plot_interactive,
    variance_function_plot_interactive,
    glm_diagnostic_panel_interactive,
    quantile_regression_band_interactive,
    quantile_loss_curve_interactive,
    huber_vs_ols_overlay_interactive,
    weighted_residual_plot_interactive,
    km_predicted_vs_observed_interactive,
    cox_residual_plot_interactive,
    proportional_hazards_test_plot_interactive,
    forecast_vs_actual_interactive,
    forecast_error_over_horizon_interactive,
    rolling_forecast_origin_interactive,
    backtest_error_distribution_interactive,
    expanding_window_metric_curve_interactive,
    forecast_band_plot_interactive,
    spatial_residual_map_interactive,
    moran_scatter_interactive,
    panel_residual_heatmap_interactive,
    vif_bar_interactive,
    condition_index_plot_interactive,
    correlation_heatmap_with_clustering_interactive,
    eigenvalue_scree_predictors_interactive,
    tolerance_bar_interactive,
    partial_dependence_regression_interactive,
    ice_plot_regression_interactive,
    marginal_effects_plot_interactive,
    interaction_effect_plot_interactive,
    conditional_expectation_curve_interactive,
    elasticity_plot_interactive,
    normality_test_panel_interactive,
    breusch_pagan_plot_interactive,
    white_test_plot_interactive,
    durbin_watson_gauge_interactive,
    ljung_box_plot_interactive,
    residual_dependence_test_panel_interactive,
    aic_bic_bar_interactive,
    nested_model_comparison_plot_interactive,
    stepwise_selection_path_interactive,
    forward_selection_score_curve_interactive,
    best_subset_metric_bar_interactive,
    learning_curve_with_band_interactive,
    nested_cv_score_plot_interactive,
    cv_residual_distribution_interactive,
    repeated_kfold_violin_interactive,
    group_cv_score_strip_interactive,
    conformal_interval_plot_interactive,
    jackknife_plus_band_interactive,
    quantile_calibration_plot_interactive,
    sharpness_vs_coverage_plot_interactive,
    coverage_by_segment_bar_interactive,
    loss_distribution_violin_interactive,
    ranked_error_plot_interactive,
    worst_k_predictions_chart_interactive,
    error_decomposition_bar_interactive,
    random_effect_caterpillar_interactive,
    random_intercept_slope_scatter_interactive,
    group_means_vs_predicted_interactive,
    boxcox_likelihood_curve_interactive,
    yeojohnson_lambda_search_interactive,
    log_log_diagnostic_interactive,
    power_transform_residual_panel_interactive,
    target_vs_feature_smooth_grid_interactive,
    feature_target_correlation_bar_interactive,
    target_encoding_curve_interactive,
    posterior_coefficient_density_interactive,
    posterior_predictive_check_interactive,
    trace_plot_coefficients_interactive,
    credible_interval_forest_interactive,
    multi_model_pred_vs_actual_overlay_interactive,
    residual_density_overlay_multi_interactive,
    error_ecdf_overlay_interactive,
    model_winner_heatmap_interactive,
    price_elasticity_curve_interactive,
    dose_response_curve_interactive,
    demand_forecast_fan_chart_interactive,
    yield_curve_fit_plot_interactive,
)
from .classification import (
    confusion_matrix_plot_interactive,
    roc_curve_interactive,
    precision_recall_curve_interactive,
)
from .spc import (
    control_chart_interactive,
    x_range_chart_interactive,
    moving_range_chart_interactive,
    xbar_r_chart_interactive,
    xbar_s_chart_interactive,
    ewma_chart_interactive,
    cusum_chart_interactive,
    p_chart_interactive,
    np_chart_interactive,
    c_chart_interactive,
    u_chart_interactive,
    capability_histogram_interactive,
    run_chart_interactive,
    rule_violation_chart_interactive,
    pareto_chart_interactive,
    process_distribution_interactive,
    zone_chart_interactive,
    hotelling_t2_chart_interactive,
    spc_dashboard_interactive,
)

# Static versions also re-exported under their canonical *_static names so that
# code following the documented `name_static` / `name_interactive` / `name`
# convention works at the top-level namespace (see project README and
# user_guide).
from .univariate import (  # noqa: F401,E402
    histogram_static,
    density_static,
    box_plot_static,
    violin_plot_static,
    frequency_bar_static,
    ecdf_plot_static,
    cumulative_histogram_static,
    qq_plot_static,
    pp_plot_static,
    outlier_plot_static,
    percentile_plot_static,
    univariate_diagnostic_panel_static,
    fitted_distribution_histogram_static,
    robust_location_plot_static,
    rug_plot_static,
    strip_plot_static,
    dot_plot_static,
    lollipop_chart_static,
    reference_band_histogram_static,
    raincloud_plot_static,
    ridgeline_plot_static,
    transformation_comparison_static,
    event_frequency_plot_static,
    interarrival_plot_static,
    univariate_analysis_dashboard_static,
    weighted_histogram_static,
    quality_bar_static,
    survival_curve_static,
    lorenz_curve_static,
    bootstrap_distribution_plot_static,
    boolean_bar_static,
    top_terms_bar_static,
    weighted_ecdf_plot_static,
    ordinal_bar_static,
    outlier_treatment_comparison_static,
)
from .bivariate import (  # noqa: F401,E402
    scatter_plot_static,
    line_plot_static,
    correlation_heatmap_static,
    bubble_plot_static,
    hexbin_plot_static,
    regression_plot_static,
    density_contour_static,
    grouped_bar_static,
    box_by_category_static,
    violin_by_category_static,
    crosstab_heatmap_static,
    binned_mean_plot_static,
    errorbar_plot_static,
    area_between_static,
    step_plot_static,
    joint_scatter_hist_static,
    bivariate_histogram_static,
    outlier_scatter_static,
    residual_relationship_static,
    quantile_bin_plot_static,
    bland_altman_static,
    rank_scatter_static,
    lag_plot_static,
    conditional_box_static,
)
from .eda import (  # noqa: F401,E402
    missing_data_plot_static,
    distribution_summary_static,
    class_distribution_static,
)
from .regression import (  # noqa: F401,E402
    residual_plot_static,
    prediction_plot_static,
    learning_curve_static,
    residual_histogram_static,
    residual_density_static,
    residual_qq_static,
    residual_boxplot_by_group_static,
    standardized_residual_plot_static,
    scale_location_plot_static,
    residual_vs_feature_static,
    partial_residual_plot_static,
    ccpr_plot_static,
    added_variable_plot_static,
    residual_acf_static,
    residual_pacf_static,
    residual_runs_plot_static,
    residual_time_plot_static,
    pred_vs_actual_hexbin_static,
    pred_vs_actual_density_static,
    prediction_error_histogram_static,
    prediction_interval_plot_static,
    error_by_magnitude_plot_static,
    leverage_plot_static,
    cooks_distance_plot_static,
    influence_bubble_plot_static,
    dfbetas_plot_static,
    coefficient_plot_static,
    coefficient_forest_plot_static,
    standardized_coefficient_plot_static,
    coefficient_path_plot_static,
    feature_importance_regression_static,
    permutation_importance_regression_static,
    lasso_path_static,
    ridge_path_static,
    regularization_validation_plot_static,
    regression_metrics_bar_static,
    metric_comparison_bar_static,
    metric_radar_static,
    per_segment_metrics_heatmap_static,
    validation_curve_static,
    training_history_static,
    cv_score_plot_static,
    bias_variance_plot_static,
    calibration_curve_regression_static,
    prediction_interval_coverage_plot_static,
    uncertainty_band_plot_static,
    regression_diagnostic_panel_static,
    regression_dashboard_static,
    # Batch-2 static variants
    link_function_plot_static,
    deviance_residual_plot_static,
    pearson_residual_plot_static,
    working_residual_plot_static,
    variance_function_plot_static,
    glm_diagnostic_panel_static,
    quantile_regression_band_static,
    quantile_loss_curve_static,
    huber_vs_ols_overlay_static,
    weighted_residual_plot_static,
    km_predicted_vs_observed_static,
    cox_residual_plot_static,
    proportional_hazards_test_plot_static,
    forecast_vs_actual_static,
    forecast_error_over_horizon_static,
    rolling_forecast_origin_static,
    backtest_error_distribution_static,
    expanding_window_metric_curve_static,
    forecast_band_plot_static,
    spatial_residual_map_static,
    moran_scatter_static,
    panel_residual_heatmap_static,
    vif_bar_static,
    condition_index_plot_static,
    correlation_heatmap_with_clustering_static,
    eigenvalue_scree_predictors_static,
    tolerance_bar_static,
    partial_dependence_regression_static,
    ice_plot_regression_static,
    marginal_effects_plot_static,
    interaction_effect_plot_static,
    conditional_expectation_curve_static,
    elasticity_plot_static,
    normality_test_panel_static,
    breusch_pagan_plot_static,
    white_test_plot_static,
    durbin_watson_gauge_static,
    ljung_box_plot_static,
    residual_dependence_test_panel_static,
    aic_bic_bar_static,
    nested_model_comparison_plot_static,
    stepwise_selection_path_static,
    forward_selection_score_curve_static,
    best_subset_metric_bar_static,
    learning_curve_with_band_static,
    nested_cv_score_plot_static,
    cv_residual_distribution_static,
    repeated_kfold_violin_static,
    group_cv_score_strip_static,
    conformal_interval_plot_static,
    jackknife_plus_band_static,
    quantile_calibration_plot_static,
    sharpness_vs_coverage_plot_static,
    coverage_by_segment_bar_static,
    loss_distribution_violin_static,
    ranked_error_plot_static,
    worst_k_predictions_chart_static,
    error_decomposition_bar_static,
    random_effect_caterpillar_static,
    random_intercept_slope_scatter_static,
    group_means_vs_predicted_static,
    boxcox_likelihood_curve_static,
    yeojohnson_lambda_search_static,
    log_log_diagnostic_static,
    power_transform_residual_panel_static,
    target_vs_feature_smooth_grid_static,
    feature_target_correlation_bar_static,
    target_encoding_curve_static,
    posterior_coefficient_density_static,
    posterior_predictive_check_static,
    trace_plot_coefficients_static,
    credible_interval_forest_static,
    multi_model_pred_vs_actual_overlay_static,
    residual_density_overlay_multi_static,
    error_ecdf_overlay_static,
    model_winner_heatmap_static,
    price_elasticity_curve_static,
    dose_response_curve_static,
    demand_forecast_fan_chart_static,
    yield_curve_fit_plot_static,
)
from .classification import (  # noqa: F401,E402
    confusion_matrix_plot_static,
    roc_curve_static,
    precision_recall_curve_static,
)
from .spc import (  # noqa: F401,E402
    control_chart_static,
    x_range_chart_static,
    moving_range_chart_static,
    xbar_r_chart_static,
    xbar_s_chart_static,
    ewma_chart_static,
    cusum_chart_static,
    p_chart_static,
    np_chart_static,
    c_chart_static,
    u_chart_static,
    capability_histogram_static,
    run_chart_static,
    rule_violation_chart_static,
    process_distribution_static,
    zone_chart_static,
    hotelling_t2_chart_static,
    spc_dashboard_static,
)
from .spc import pareto_chart_static as spc_pareto_chart_static  # noqa: F401,E402
from .univariate import pareto_chart_static as univariate_pareto_chart_static  # noqa: F401,E402

__all__ = [
    # Submodules
    "spc",
    "univariate",
    "bivariate",
    "multivariate",
    "eda",
    "xai",
    "regression",
    "classification",
    "clustering",
    "utils",
    "types",
    # Univariate - static
    "histogram",
    "density_plot",
    "box_plot",
    "violin_plot",
    "frequency_bar",
    "univariate_pareto_chart",
    "ecdf_plot",
    "cumulative_histogram",
    "qq_plot",
    "pp_plot",
    "outlier_plot",
    "percentile_plot",
    "univariate_diagnostic_panel",
    "fitted_distribution_histogram",
    "robust_location_plot",
    "rug_plot",
    "strip_plot",
    "dot_plot",
    "lollipop_chart",
    "reference_band_histogram",
    "raincloud_plot",
    "ridgeline_plot",
    "transformation_comparison",
    "event_frequency_plot",
    "interarrival_plot",
    "univariate_analysis_dashboard",
    "weighted_histogram",
    "quality_bar",
    "survival_curve",
    "lorenz_curve",
    "bootstrap_distribution_plot",
    "boolean_bar",
    "top_terms_bar",
    "weighted_ecdf_plot",
    "ordinal_bar",
    "outlier_treatment_comparison",
    "auto_profile_chart",
    "UnivariateInput",
    "UnivariateStats",
    "RobustStats",
    "DistributionFit",
    "TransformResult",
    "NormalityTestResult",
    "WeightedStats",
    "DataQualitySummary",
    "ConcentrationStats",
    "BootstrapCI",
    "BooleanSummary",
    "BooleanRateInterval",
    "OutlierTreatmentResult",
    "UnivariateProfile",
    "as_datetime_series",
    "resolve_weighted_series",
    "resolve_univariate_data",
    "infer_univariate_kind",
    "numeric_or_none",
    "category_counts",
    "ordered_category_counts",
    "ecdf_values",
    "survival_values",
    "lorenz_curve_values",
    "univariate_summary",
    "robust_summary",
    "weighted_summary",
    "data_quality_summary",
    "sentinel_value_counts",
    "sentinel_rate",
    "concentration_summary",
    "normality_test",
    "fit_distribution",
    "compare_distributions",
    "fitted_pdf_values",
    "transform_series",
    "transformation_summary",
    "event_counts",
    "interarrival_times",
    "exceedance_table",
    "bootstrap_distribution",
    "bootstrap_ci",
    "boolean_summary",
    "boolean_wilson_interval",
    "string_length_summary",
    "token_count_summary",
    "top_terms",
    "likert_summary",
    "auto_profile",
    "iqr_outliers",
    "zscore_outliers",
    "mad_outliers",
    "mad_zscores",
    "trimmed_mean",
    "winsorize_series",
    "weighted_quantile",
    "weighted_ecdf_values",
    "outlier_mask",
    "cap_outliers",
    "remove_outliers",
    "flag_outliers",
    "recommended_bin_count",
    "percentile_table",
    # Univariate - interactive
    "histogram_interactive",
    "density_interactive",
    "box_plot_interactive",
    "violin_plot_interactive",
    "frequency_bar_interactive",
    "univariate_pareto_chart_interactive",
    "ecdf_plot_interactive",
    "cumulative_histogram_interactive",
    "qq_plot_interactive",
    "pp_plot_interactive",
    "outlier_plot_interactive",
    "percentile_plot_interactive",
    "univariate_diagnostic_panel_interactive",
    "fitted_distribution_histogram_interactive",
    "robust_location_plot_interactive",
    "rug_plot_interactive",
    "strip_plot_interactive",
    "dot_plot_interactive",
    "lollipop_chart_interactive",
    "reference_band_histogram_interactive",
    "raincloud_plot_interactive",
    "ridgeline_plot_interactive",
    "transformation_comparison_interactive",
    "event_frequency_plot_interactive",
    "interarrival_plot_interactive",
    "univariate_analysis_dashboard_interactive",
    "weighted_histogram_interactive",
    "quality_bar_interactive",
    "survival_curve_interactive",
    "lorenz_curve_interactive",
    "bootstrap_distribution_plot_interactive",
    "boolean_bar_interactive",
    "top_terms_bar_interactive",
    "weighted_ecdf_plot_interactive",
    "ordinal_bar_interactive",
    "outlier_treatment_comparison_interactive",
    "auto_profile_chart_interactive",
    # Bivariate - static
    "scatter_plot",
    "line_plot",
    "correlation_heatmap",
    "bubble_plot",
    "hexbin_plot",
    "regression_plot",
    "density_contour",
    "grouped_bar",
    "box_by_category",
    "violin_by_category",
    "crosstab_heatmap",
    "binned_mean_plot",
    "errorbar_plot",
    "area_between",
    "step_plot",
    "joint_scatter_hist",
    "bivariate_histogram",
    "BivariateStats",
    "bivariate_summary",
    "outlier_scatter",
    "residual_relationship",
    "quantile_bin_plot",
    "bland_altman",
    "rank_scatter",
    "lag_plot",
    "conditional_box",
    # Bivariate - interactive
    "scatter_plot_interactive",
    "line_plot_interactive",
    "correlation_heatmap_interactive",
    "bubble_plot_interactive",
    "hexbin_plot_interactive",
    "regression_plot_interactive",
    "density_contour_interactive",
    "grouped_bar_interactive",
    "box_by_category_interactive",
    "violin_by_category_interactive",
    "crosstab_heatmap_interactive",
    "binned_mean_plot_interactive",
    "errorbar_plot_interactive",
    "area_between_interactive",
    "step_plot_interactive",
    "joint_scatter_hist_interactive",
    "bivariate_histogram_interactive",
    "outlier_scatter_interactive",
    "residual_relationship_interactive",
    "quantile_bin_plot_interactive",
    "bland_altman_interactive",
    "rank_scatter_interactive",
    "lag_plot_interactive",
    "conditional_box_interactive",
    # EDA - static
    "missing_data_plot",
    "distribution_summary",
    "class_distribution",
    # EDA - interactive
    "missing_data_plot_interactive",
    "distribution_summary_interactive",
    "class_distribution_interactive",
    # Regression - static
    "residual_plot",
    "prediction_plot",
    "learning_curve",
    # Regression - interactive
    "residual_plot_interactive",
    "prediction_plot_interactive",
    "learning_curve_interactive",
    # Classification - static
    "confusion_matrix_plot",
    "roc_curve",
    "precision_recall_curve",
    # Classification - interactive
    "confusion_matrix_plot_interactive",
    "roc_curve_interactive",
    "precision_recall_curve_interactive",
    # SPC - static
    "control_chart",
    "x_range_chart",
    "moving_range_chart",
    "xbar_r_chart",
    "xbar_s_chart",
    "ewma_chart",
    "cusum_chart",
    "p_chart",
    "np_chart",
    "c_chart",
    "u_chart",
    "capability_histogram",
    "run_chart",
    "rule_violation_chart",
    "pareto_chart",
    "process_distribution",
    "zone_chart",
    "hotelling_t2_chart",
    "spc_dashboard",
    # SPC - interactive
    "control_chart_interactive",
    "x_range_chart_interactive",
    "moving_range_chart_interactive",
    "xbar_r_chart_interactive",
    "xbar_s_chart_interactive",
    "ewma_chart_interactive",
    "cusum_chart_interactive",
    "p_chart_interactive",
    "np_chart_interactive",
    "c_chart_interactive",
    "u_chart_interactive",
    "capability_histogram_interactive",
    "run_chart_interactive",
    "rule_violation_chart_interactive",
    "pareto_chart_interactive",
    "process_distribution_interactive",
    "zone_chart_interactive",
    "hotelling_t2_chart_interactive",
    "spc_dashboard_interactive",
    # SPC helpers
    "ControlLimits",
    "RuleViolation",
    "SPCConstants",
    "SPC_CONSTANTS",
    "CapabilityStats",
    "HotellingT2Result",
    "capability_summary",
    "hotelling_t2_summary",
    "detect_rule_violations",
    "get_spc_constants",
    # Regression - helpers and result types
    "RegressionMetrics",
    "InfluenceStatistics",
    "compute_regression_metrics",
    "influence_statistics",
    "prediction_intervals",
    "coefficient_table",
    "autocorrelation",
    "partial_autocorrelation",
    "runs_test_signs",
    "compute_regularization_path",
    # Regression - static (aliases default to static)
    "residual_histogram", "residual_density", "residual_qq",
    "residual_boxplot_by_group", "standardized_residual_plot",
    "scale_location_plot", "residual_vs_feature", "partial_residual_plot",
    "ccpr_plot", "added_variable_plot", "residual_acf", "residual_pacf",
    "residual_runs_plot", "residual_time_plot", "pred_vs_actual_hexbin",
    "pred_vs_actual_density", "prediction_error_histogram",
    "prediction_interval_plot", "error_by_magnitude_plot", "leverage_plot",
    "cooks_distance_plot", "influence_bubble_plot", "dfbetas_plot",
    "coefficient_plot", "coefficient_forest_plot",
    "standardized_coefficient_plot", "coefficient_path_plot",
    "feature_importance_regression", "permutation_importance_regression",
    "lasso_path", "ridge_path", "regularization_validation_plot",
    "regression_metrics_bar", "metric_comparison_bar", "metric_radar",
    "per_segment_metrics_heatmap", "validation_curve", "training_history",
    "cv_score_plot", "bias_variance_plot", "calibration_curve_regression",
    "prediction_interval_coverage_plot", "uncertainty_band_plot",
    "regression_diagnostic_panel", "regression_dashboard",
    # Regression - explicit *_static names
    "residual_histogram_static", "residual_density_static",
    "residual_qq_static", "residual_boxplot_by_group_static",
    "standardized_residual_plot_static", "scale_location_plot_static",
    "residual_vs_feature_static", "partial_residual_plot_static",
    "ccpr_plot_static", "added_variable_plot_static", "residual_acf_static",
    "residual_pacf_static", "residual_runs_plot_static",
    "residual_time_plot_static", "pred_vs_actual_hexbin_static",
    "pred_vs_actual_density_static", "prediction_error_histogram_static",
    "prediction_interval_plot_static", "error_by_magnitude_plot_static",
    "leverage_plot_static", "cooks_distance_plot_static",
    "influence_bubble_plot_static", "dfbetas_plot_static",
    "coefficient_plot_static", "coefficient_forest_plot_static",
    "standardized_coefficient_plot_static", "coefficient_path_plot_static",
    "feature_importance_regression_static",
    "permutation_importance_regression_static", "lasso_path_static",
    "ridge_path_static", "regularization_validation_plot_static",
    "regression_metrics_bar_static", "metric_comparison_bar_static",
    "metric_radar_static", "per_segment_metrics_heatmap_static",
    "validation_curve_static", "training_history_static",
    "cv_score_plot_static", "bias_variance_plot_static",
    "calibration_curve_regression_static",
    "prediction_interval_coverage_plot_static",
    "uncertainty_band_plot_static", "regression_diagnostic_panel_static",
    "regression_dashboard_static",
    # Regression - explicit *_interactive names
    "residual_histogram_interactive", "residual_density_interactive",
    "residual_qq_interactive", "residual_boxplot_by_group_interactive",
    "standardized_residual_plot_interactive",
    "scale_location_plot_interactive", "residual_vs_feature_interactive",
    "partial_residual_plot_interactive", "ccpr_plot_interactive",
    "added_variable_plot_interactive", "residual_acf_interactive",
    "residual_pacf_interactive", "residual_runs_plot_interactive",
    "residual_time_plot_interactive", "pred_vs_actual_hexbin_interactive",
    "pred_vs_actual_density_interactive",
    "prediction_error_histogram_interactive",
    "prediction_interval_plot_interactive",
    "error_by_magnitude_plot_interactive", "leverage_plot_interactive",
    "cooks_distance_plot_interactive", "influence_bubble_plot_interactive",
    "dfbetas_plot_interactive", "coefficient_plot_interactive",
    "coefficient_forest_plot_interactive",
    "standardized_coefficient_plot_interactive",
    "coefficient_path_plot_interactive",
    "feature_importance_regression_interactive",
    "permutation_importance_regression_interactive",
    "lasso_path_interactive", "ridge_path_interactive",
    "regularization_validation_plot_interactive",
    "regression_metrics_bar_interactive",
    "metric_comparison_bar_interactive", "metric_radar_interactive",
    "per_segment_metrics_heatmap_interactive",
    "validation_curve_interactive", "training_history_interactive",
    "cv_score_plot_interactive", "bias_variance_plot_interactive",
    "calibration_curve_regression_interactive",
    "prediction_interval_coverage_plot_interactive",
    "uncertainty_band_plot_interactive",
    "regression_diagnostic_panel_interactive",
    "regression_dashboard_interactive",
    # Batch-2 helpers
    "variance_inflation_factors", "breusch_pagan_statistic",
    "white_test_statistic", "ljung_box_statistic", "jarque_bera_statistic",
    "durbin_watson_statistic", "box_cox_loglikelihood",
    "yeo_johnson_loglikelihood", "conformal_quantile",
    "jackknife_plus_intervals",
    # Batch-2 aliases
    "link_function_plot", "deviance_residual_plot", "pearson_residual_plot",
    "working_residual_plot", "variance_function_plot", "glm_diagnostic_panel",
    "quantile_regression_band", "quantile_loss_curve", "huber_vs_ols_overlay",
    "weighted_residual_plot", "km_predicted_vs_observed", "cox_residual_plot",
    "proportional_hazards_test_plot", "forecast_vs_actual",
    "forecast_error_over_horizon", "rolling_forecast_origin",
    "backtest_error_distribution", "expanding_window_metric_curve",
    "forecast_band_plot", "spatial_residual_map", "moran_scatter",
    "panel_residual_heatmap", "vif_bar", "condition_index_plot",
    "correlation_heatmap_with_clustering", "eigenvalue_scree_predictors",
    "tolerance_bar", "partial_dependence_regression", "ice_plot_regression",
    "marginal_effects_plot", "interaction_effect_plot",
    "conditional_expectation_curve", "elasticity_plot", "normality_test_panel",
    "breusch_pagan_plot", "white_test_plot", "durbin_watson_gauge",
    "ljung_box_plot", "residual_dependence_test_panel", "aic_bic_bar",
    "nested_model_comparison_plot", "stepwise_selection_path",
    "forward_selection_score_curve", "best_subset_metric_bar",
    "learning_curve_with_band", "nested_cv_score_plot",
    "cv_residual_distribution", "repeated_kfold_violin", "group_cv_score_strip",
    "conformal_interval_plot", "jackknife_plus_band", "quantile_calibration_plot",
    "sharpness_vs_coverage_plot", "coverage_by_segment_bar",
    "loss_distribution_violin", "ranked_error_plot", "worst_k_predictions_chart",
    "error_decomposition_bar", "random_effect_caterpillar",
    "random_intercept_slope_scatter", "group_means_vs_predicted",
    "boxcox_likelihood_curve", "yeojohnson_lambda_search", "log_log_diagnostic",
    "power_transform_residual_panel", "target_vs_feature_smooth_grid",
    "feature_target_correlation_bar", "target_encoding_curve",
    "posterior_coefficient_density", "posterior_predictive_check",
    "trace_plot_coefficients", "credible_interval_forest",
    "multi_model_pred_vs_actual_overlay", "residual_density_overlay_multi",
    "error_ecdf_overlay", "model_winner_heatmap", "price_elasticity_curve",
    "dose_response_curve", "demand_forecast_fan_chart", "yield_curve_fit_plot",
    # Batch-2 explicit *_static / *_interactive
    "link_function_plot_static", "link_function_plot_interactive",
    "deviance_residual_plot_static", "deviance_residual_plot_interactive",
    "pearson_residual_plot_static", "pearson_residual_plot_interactive",
    "working_residual_plot_static", "working_residual_plot_interactive",
    "variance_function_plot_static", "variance_function_plot_interactive",
    "glm_diagnostic_panel_static", "glm_diagnostic_panel_interactive",
    "quantile_regression_band_static", "quantile_regression_band_interactive",
    "quantile_loss_curve_static", "quantile_loss_curve_interactive",
    "huber_vs_ols_overlay_static", "huber_vs_ols_overlay_interactive",
    "weighted_residual_plot_static", "weighted_residual_plot_interactive",
    "km_predicted_vs_observed_static", "km_predicted_vs_observed_interactive",
    "cox_residual_plot_static", "cox_residual_plot_interactive",
    "proportional_hazards_test_plot_static",
    "proportional_hazards_test_plot_interactive",
    "forecast_vs_actual_static", "forecast_vs_actual_interactive",
    "forecast_error_over_horizon_static",
    "forecast_error_over_horizon_interactive",
    "rolling_forecast_origin_static", "rolling_forecast_origin_interactive",
    "backtest_error_distribution_static",
    "backtest_error_distribution_interactive",
    "expanding_window_metric_curve_static",
    "expanding_window_metric_curve_interactive",
    "forecast_band_plot_static", "forecast_band_plot_interactive",
    "spatial_residual_map_static", "spatial_residual_map_interactive",
    "moran_scatter_static", "moran_scatter_interactive",
    "panel_residual_heatmap_static", "panel_residual_heatmap_interactive",
    "vif_bar_static", "vif_bar_interactive",
    "condition_index_plot_static", "condition_index_plot_interactive",
    "correlation_heatmap_with_clustering_static",
    "correlation_heatmap_with_clustering_interactive",
    "eigenvalue_scree_predictors_static",
    "eigenvalue_scree_predictors_interactive",
    "tolerance_bar_static", "tolerance_bar_interactive",
    "partial_dependence_regression_static",
    "partial_dependence_regression_interactive",
    "ice_plot_regression_static", "ice_plot_regression_interactive",
    "marginal_effects_plot_static", "marginal_effects_plot_interactive",
    "interaction_effect_plot_static", "interaction_effect_plot_interactive",
    "conditional_expectation_curve_static",
    "conditional_expectation_curve_interactive",
    "elasticity_plot_static", "elasticity_plot_interactive",
    "normality_test_panel_static", "normality_test_panel_interactive",
    "breusch_pagan_plot_static", "breusch_pagan_plot_interactive",
    "white_test_plot_static", "white_test_plot_interactive",
    "durbin_watson_gauge_static", "durbin_watson_gauge_interactive",
    "ljung_box_plot_static", "ljung_box_plot_interactive",
    "residual_dependence_test_panel_static",
    "residual_dependence_test_panel_interactive",
    "aic_bic_bar_static", "aic_bic_bar_interactive",
    "nested_model_comparison_plot_static",
    "nested_model_comparison_plot_interactive",
    "stepwise_selection_path_static", "stepwise_selection_path_interactive",
    "forward_selection_score_curve_static",
    "forward_selection_score_curve_interactive",
    "best_subset_metric_bar_static", "best_subset_metric_bar_interactive",
    "learning_curve_with_band_static", "learning_curve_with_band_interactive",
    "nested_cv_score_plot_static", "nested_cv_score_plot_interactive",
    "cv_residual_distribution_static", "cv_residual_distribution_interactive",
    "repeated_kfold_violin_static", "repeated_kfold_violin_interactive",
    "group_cv_score_strip_static", "group_cv_score_strip_interactive",
    "conformal_interval_plot_static", "conformal_interval_plot_interactive",
    "jackknife_plus_band_static", "jackknife_plus_band_interactive",
    "quantile_calibration_plot_static", "quantile_calibration_plot_interactive",
    "sharpness_vs_coverage_plot_static",
    "sharpness_vs_coverage_plot_interactive",
    "coverage_by_segment_bar_static", "coverage_by_segment_bar_interactive",
    "loss_distribution_violin_static", "loss_distribution_violin_interactive",
    "ranked_error_plot_static", "ranked_error_plot_interactive",
    "worst_k_predictions_chart_static", "worst_k_predictions_chart_interactive",
    "error_decomposition_bar_static", "error_decomposition_bar_interactive",
    "random_effect_caterpillar_static",
    "random_effect_caterpillar_interactive",
    "random_intercept_slope_scatter_static",
    "random_intercept_slope_scatter_interactive",
    "group_means_vs_predicted_static", "group_means_vs_predicted_interactive",
    "boxcox_likelihood_curve_static", "boxcox_likelihood_curve_interactive",
    "yeojohnson_lambda_search_static", "yeojohnson_lambda_search_interactive",
    "log_log_diagnostic_static", "log_log_diagnostic_interactive",
    "power_transform_residual_panel_static",
    "power_transform_residual_panel_interactive",
    "target_vs_feature_smooth_grid_static",
    "target_vs_feature_smooth_grid_interactive",
    "feature_target_correlation_bar_static",
    "feature_target_correlation_bar_interactive",
    "target_encoding_curve_static", "target_encoding_curve_interactive",
    "posterior_coefficient_density_static",
    "posterior_coefficient_density_interactive",
    "posterior_predictive_check_static",
    "posterior_predictive_check_interactive",
    "trace_plot_coefficients_static", "trace_plot_coefficients_interactive",
    "credible_interval_forest_static", "credible_interval_forest_interactive",
    "multi_model_pred_vs_actual_overlay_static",
    "multi_model_pred_vs_actual_overlay_interactive",
    "residual_density_overlay_multi_static",
    "residual_density_overlay_multi_interactive",
    "error_ecdf_overlay_static", "error_ecdf_overlay_interactive",
    "model_winner_heatmap_static", "model_winner_heatmap_interactive",
    "price_elasticity_curve_static", "price_elasticity_curve_interactive",
    "dose_response_curve_static", "dose_response_curve_interactive",
    "demand_forecast_fan_chart_static",
    "demand_forecast_fan_chart_interactive",
    "yield_curve_fit_plot_static", "yield_curve_fit_plot_interactive",
]
