"""
DataViz - A comprehensive data visualization package.

This package provides easy-to-use tools for creating beautiful visualizations
organized by chart type and analysis category. Each chart has both static
(matplotlib/seaborn) and interactive (plotly) versions.

Usage Examples
--------------

Static (default, matplotlib-based):
    >>> import dataviz as dv
    >>> dv.histogram(data)  # Uses histogram_static
    >>> dv.scatter_plot(x, y)  # Uses scatter_plot_static

Interactive (plotly-based):
    >>> dv.histogram_interactive(data)
    >>> dv.scatter_plot_interactive(x, y)

Or access via submodules:
    >>> dv.univariate.histogram_static(data)
    >>> dv.univariate.histogram_interactive(data)
"""

__version__ = "0.1.0"
__author__ = "PhD Aned Esquerra-Arguelles"
__email__ = "aned.ezquerra@gmail.com"

# Import submodules
from . import spc
from . import univariate
from . import bivariate
from . import multivariate
from . import eda
from . import xai
from . import regression
from . import classification
from . import clustering
from . import utils
from . import types

# Convenience imports - Static versions (default)
from .univariate import (
    histogram_static as histogram,
    density_static as density_plot,
    box_plot_static as box_plot,
    violin_plot_static as violin_plot,
    frequency_bar_static as frequency_bar,
    pareto_chart_static as univariate_pareto_chart,
    ecdf_plot_static as ecdf_plot,
    cumulative_histogram_static as cumulative_histogram,
    qq_plot_static as qq_plot,
    pp_plot_static as pp_plot,
    outlier_plot_static as outlier_plot,
    percentile_plot_static as percentile_plot,
    univariate_diagnostic_panel_static as univariate_diagnostic_panel,
    fitted_distribution_histogram_static as fitted_distribution_histogram,
    robust_location_plot_static as robust_location_plot,
    rug_plot_static as rug_plot,
    strip_plot_static as strip_plot,
    dot_plot_static as dot_plot,
    lollipop_chart_static as lollipop_chart,
    reference_band_histogram_static as reference_band_histogram,
    raincloud_plot_static as raincloud_plot,
    ridgeline_plot_static as ridgeline_plot,
    transformation_comparison_static as transformation_comparison,
    event_frequency_plot_static as event_frequency_plot,
    interarrival_plot_static as interarrival_plot,
    univariate_analysis_dashboard_static as univariate_analysis_dashboard,
    weighted_histogram_static as weighted_histogram,
    quality_bar_static as quality_bar,
    survival_curve_static as survival_curve,
    lorenz_curve_static as lorenz_curve,
    bootstrap_distribution_plot_static as bootstrap_distribution_plot,
    boolean_bar_static as boolean_bar,
    top_terms_bar_static as top_terms_bar,
    weighted_ecdf_plot_static as weighted_ecdf_plot,
    ordinal_bar_static as ordinal_bar,
    outlier_treatment_comparison_static as outlier_treatment_comparison,
    auto_profile_chart_interactive as auto_profile_chart,
    UnivariateInput,
    UnivariateStats,
    RobustStats,
    DistributionFit,
    TransformResult,
    NormalityTestResult,
    WeightedStats,
    DataQualitySummary,
    ConcentrationStats,
    BootstrapCI,
    BooleanSummary,
    BooleanRateInterval,
    OutlierTreatmentResult,
    UnivariateProfile,
    as_datetime_series,
    resolve_weighted_series,
    resolve_univariate_data,
    infer_univariate_kind,
    numeric_or_none,
    category_counts,
    ordered_category_counts,
    ecdf_values,
    survival_values,
    lorenz_curve_values,
    univariate_summary,
    robust_summary,
    weighted_summary,
    data_quality_summary,
    sentinel_value_counts,
    sentinel_rate,
    concentration_summary,
    normality_test,
    fit_distribution,
    compare_distributions,
    fitted_pdf_values,
    transform_series,
    transformation_summary,
    event_counts,
    interarrival_times,
    exceedance_table,
    bootstrap_distribution,
    bootstrap_ci,
    boolean_summary,
    boolean_wilson_interval,
    string_length_summary,
    token_count_summary,
    top_terms,
    likert_summary,
    auto_profile,
    iqr_outliers,
    zscore_outliers,
    mad_outliers,
    mad_zscores,
    trimmed_mean,
    winsorize_series,
    weighted_quantile,
    weighted_ecdf_values,
    outlier_mask,
    cap_outliers,
    remove_outliers,
    flag_outliers,
    recommended_bin_count,
    percentile_table,
)
from .bivariate import (
    scatter_plot_static as scatter_plot,
    line_plot_static as line_plot,
    correlation_heatmap_static as correlation_heatmap,
    bubble_plot_static as bubble_plot,
    hexbin_plot_static as hexbin_plot,
    regression_plot_static as regression_plot,
    density_contour_static as density_contour,
    grouped_bar_static as grouped_bar,
    box_by_category_static as box_by_category,
    violin_by_category_static as violin_by_category,
    crosstab_heatmap_static as crosstab_heatmap,
    binned_mean_plot_static as binned_mean_plot,
    errorbar_plot_static as errorbar_plot,
    area_between_static as area_between,
    step_plot_static as step_plot,
    joint_scatter_hist_static as joint_scatter_hist,
    bivariate_histogram_static as bivariate_histogram,
    BivariateStats,
    bivariate_summary,
    outlier_scatter_static as outlier_scatter,
    residual_relationship_static as residual_relationship,
    quantile_bin_plot_static as quantile_bin_plot,
    bland_altman_static as bland_altman,
    rank_scatter_static as rank_scatter,
    lag_plot_static as lag_plot,
    conditional_box_static as conditional_box,
)
from .eda import (
    missing_data_plot_static as missing_data_plot,
    distribution_summary_static as distribution_summary,
    class_distribution_static as class_distribution,
)
from .regression import (
    residual_plot_static as residual_plot,
    prediction_plot_static as prediction_plot,
    learning_curve_static as learning_curve,
)
from .classification import (
    confusion_matrix_plot_static as confusion_matrix_plot,
    roc_curve_static as roc_curve,
    precision_recall_curve_static as precision_recall_curve,
)
from .spc import (
    control_chart_static as control_chart,
    x_range_chart_static as x_range_chart,
    moving_range_chart_static as moving_range_chart,
    xbar_r_chart_static as xbar_r_chart,
    xbar_s_chart_static as xbar_s_chart,
    ewma_chart_static as ewma_chart,
    cusum_chart_static as cusum_chart,
    p_chart_static as p_chart,
    np_chart_static as np_chart,
    c_chart_static as c_chart,
    u_chart_static as u_chart,
    capability_histogram_static as capability_histogram,
    ControlLimits,
    RuleViolation,
    SPCConstants,
    SPC_CONSTANTS,
    CapabilityStats,
    HotellingT2Result,
    capability_summary,
    hotelling_t2_summary,
    detect_rule_violations,
    get_spc_constants,
    run_chart_static as run_chart,
    rule_violation_chart_static as rule_violation_chart,
    pareto_chart_static as pareto_chart,
    process_distribution_static as process_distribution,
    zone_chart_static as zone_chart,
    hotelling_t2_chart_static as hotelling_t2_chart,
    spc_dashboard_static as spc_dashboard,
)

# Interactive versions imports
from .univariate import (
    histogram_interactive,
    density_interactive,
    box_plot_interactive,
    violin_plot_interactive,
    frequency_bar_interactive,
    pareto_chart_interactive as univariate_pareto_chart_interactive,
    ecdf_plot_interactive,
    cumulative_histogram_interactive,
    qq_plot_interactive,
    pp_plot_interactive,
    outlier_plot_interactive,
    percentile_plot_interactive,
    univariate_diagnostic_panel_interactive,
    fitted_distribution_histogram_interactive,
    robust_location_plot_interactive,
    rug_plot_interactive,
    strip_plot_interactive,
    dot_plot_interactive,
    lollipop_chart_interactive,
    reference_band_histogram_interactive,
    raincloud_plot_interactive,
    ridgeline_plot_interactive,
    transformation_comparison_interactive,
    event_frequency_plot_interactive,
    interarrival_plot_interactive,
    univariate_analysis_dashboard_interactive,
    weighted_histogram_interactive,
    quality_bar_interactive,
    survival_curve_interactive,
    lorenz_curve_interactive,
    bootstrap_distribution_plot_interactive,
    boolean_bar_interactive,
    top_terms_bar_interactive,
    weighted_ecdf_plot_interactive,
    ordinal_bar_interactive,
    outlier_treatment_comparison_interactive,
    auto_profile_chart_interactive,
)
from .bivariate import (
    scatter_plot_interactive,
    line_plot_interactive,
    correlation_heatmap_interactive,
    bubble_plot_interactive,
    hexbin_plot_interactive,
    regression_plot_interactive,
    density_contour_interactive,
    grouped_bar_interactive,
    box_by_category_interactive,
    violin_by_category_interactive,
    crosstab_heatmap_interactive,
    binned_mean_plot_interactive,
    errorbar_plot_interactive,
    area_between_interactive,
    step_plot_interactive,
    joint_scatter_hist_interactive,
    bivariate_histogram_interactive,
    outlier_scatter_interactive,
    residual_relationship_interactive,
    quantile_bin_plot_interactive,
    bland_altman_interactive,
    rank_scatter_interactive,
    lag_plot_interactive,
    conditional_box_interactive,
)
from .eda import (
    missing_data_plot_interactive,
    distribution_summary_interactive,
    class_distribution_interactive,
)
from .regression import (
    residual_plot_interactive,
    prediction_plot_interactive,
    learning_curve_interactive,
)
from .classification import (
    confusion_matrix_plot_interactive,
    roc_curve_interactive,
    precision_recall_curve_interactive,
)
from .spc import (
    control_chart_interactive,
    x_range_chart_interactive,
    moving_range_chart_interactive,
    xbar_r_chart_interactive,
    xbar_s_chart_interactive,
    ewma_chart_interactive,
    cusum_chart_interactive,
    p_chart_interactive,
    np_chart_interactive,
    c_chart_interactive,
    u_chart_interactive,
    capability_histogram_interactive,
    run_chart_interactive,
    rule_violation_chart_interactive,
    pareto_chart_interactive,
    process_distribution_interactive,
    zone_chart_interactive,
    hotelling_t2_chart_interactive,
    spc_dashboard_interactive,
)

__all__ = [
    # Submodules
    "spc",
    "univariate",
    "bivariate",
    "multivariate",
    "eda",
    "xai",
    "regression",
    "classification",
    "clustering",
    "utils",
    "types",
    # Univariate - static
    "histogram",
    "density_plot",
    "box_plot",
    "violin_plot",
    "frequency_bar",
    "univariate_pareto_chart",
    "ecdf_plot",
    "cumulative_histogram",
    "qq_plot",
    "pp_plot",
    "outlier_plot",
    "percentile_plot",
    "univariate_diagnostic_panel",
    "fitted_distribution_histogram",
    "robust_location_plot",
    "rug_plot",
    "strip_plot",
    "dot_plot",
    "lollipop_chart",
    "reference_band_histogram",
    "raincloud_plot",
    "ridgeline_plot",
    "transformation_comparison",
    "event_frequency_plot",
    "interarrival_plot",
    "univariate_analysis_dashboard",
    "weighted_histogram",
    "quality_bar",
    "survival_curve",
    "lorenz_curve",
    "bootstrap_distribution_plot",
    "boolean_bar",
    "top_terms_bar",
    "weighted_ecdf_plot",
    "ordinal_bar",
    "outlier_treatment_comparison",
    "auto_profile_chart",
    "UnivariateInput",
    "UnivariateStats",
    "RobustStats",
    "DistributionFit",
    "TransformResult",
    "NormalityTestResult",
    "WeightedStats",
    "DataQualitySummary",
    "ConcentrationStats",
    "BootstrapCI",
    "BooleanSummary",
    "BooleanRateInterval",
    "OutlierTreatmentResult",
    "UnivariateProfile",
    "as_datetime_series",
    "resolve_weighted_series",
    "resolve_univariate_data",
    "infer_univariate_kind",
    "numeric_or_none",
    "category_counts",
    "ordered_category_counts",
    "ecdf_values",
    "survival_values",
    "lorenz_curve_values",
    "univariate_summary",
    "robust_summary",
    "weighted_summary",
    "data_quality_summary",
    "sentinel_value_counts",
    "sentinel_rate",
    "concentration_summary",
    "normality_test",
    "fit_distribution",
    "compare_distributions",
    "fitted_pdf_values",
    "transform_series",
    "transformation_summary",
    "event_counts",
    "interarrival_times",
    "exceedance_table",
    "bootstrap_distribution",
    "bootstrap_ci",
    "boolean_summary",
    "boolean_wilson_interval",
    "string_length_summary",
    "token_count_summary",
    "top_terms",
    "likert_summary",
    "auto_profile",
    "iqr_outliers",
    "zscore_outliers",
    "mad_outliers",
    "mad_zscores",
    "trimmed_mean",
    "winsorize_series",
    "weighted_quantile",
    "weighted_ecdf_values",
    "outlier_mask",
    "cap_outliers",
    "remove_outliers",
    "flag_outliers",
    "recommended_bin_count",
    "percentile_table",
    # Univariate - interactive
    "histogram_interactive",
    "density_interactive",
    "box_plot_interactive",
    "violin_plot_interactive",
    "frequency_bar_interactive",
    "univariate_pareto_chart_interactive",
    "ecdf_plot_interactive",
    "cumulative_histogram_interactive",
    "qq_plot_interactive",
    "pp_plot_interactive",
    "outlier_plot_interactive",
    "percentile_plot_interactive",
    "univariate_diagnostic_panel_interactive",
    "fitted_distribution_histogram_interactive",
    "robust_location_plot_interactive",
    "rug_plot_interactive",
    "strip_plot_interactive",
    "dot_plot_interactive",
    "lollipop_chart_interactive",
    "reference_band_histogram_interactive",
    "raincloud_plot_interactive",
    "ridgeline_plot_interactive",
    "transformation_comparison_interactive",
    "event_frequency_plot_interactive",
    "interarrival_plot_interactive",
    "univariate_analysis_dashboard_interactive",
    "weighted_histogram_interactive",
    "quality_bar_interactive",
    "survival_curve_interactive",
    "lorenz_curve_interactive",
    "bootstrap_distribution_plot_interactive",
    "boolean_bar_interactive",
    "top_terms_bar_interactive",
    "weighted_ecdf_plot_interactive",
    "ordinal_bar_interactive",
    "outlier_treatment_comparison_interactive",
    "auto_profile_chart_interactive",
    # Bivariate - static
    "scatter_plot",
    "line_plot",
    "correlation_heatmap",
    "bubble_plot",
    "hexbin_plot",
    "regression_plot",
    "density_contour",
    "grouped_bar",
    "box_by_category",
    "violin_by_category",
    "crosstab_heatmap",
    "binned_mean_plot",
    "errorbar_plot",
    "area_between",
    "step_plot",
    "joint_scatter_hist",
    "bivariate_histogram",
    "BivariateStats",
    "bivariate_summary",
    "outlier_scatter",
    "residual_relationship",
    "quantile_bin_plot",
    "bland_altman",
    "rank_scatter",
    "lag_plot",
    "conditional_box",
    # Bivariate - interactive
    "scatter_plot_interactive",
    "line_plot_interactive",
    "correlation_heatmap_interactive",
    "bubble_plot_interactive",
    "hexbin_plot_interactive",
    "regression_plot_interactive",
    "density_contour_interactive",
    "grouped_bar_interactive",
    "box_by_category_interactive",
    "violin_by_category_interactive",
    "crosstab_heatmap_interactive",
    "binned_mean_plot_interactive",
    "errorbar_plot_interactive",
    "area_between_interactive",
    "step_plot_interactive",
    "joint_scatter_hist_interactive",
    "bivariate_histogram_interactive",
    "outlier_scatter_interactive",
    "residual_relationship_interactive",
    "quantile_bin_plot_interactive",
    "bland_altman_interactive",
    "rank_scatter_interactive",
    "lag_plot_interactive",
    "conditional_box_interactive",
    # EDA - static
    "missing_data_plot",
    "distribution_summary",
    "class_distribution",
    # EDA - interactive
    "missing_data_plot_interactive",
    "distribution_summary_interactive",
    "class_distribution_interactive",
    # Regression - static
    "residual_plot",
    "prediction_plot",
    "learning_curve",
    # Regression - interactive
    "residual_plot_interactive",
    "prediction_plot_interactive",
    "learning_curve_interactive",
    # Classification - static
    "confusion_matrix_plot",
    "roc_curve",
    "precision_recall_curve",
    # Classification - interactive
    "confusion_matrix_plot_interactive",
    "roc_curve_interactive",
    "precision_recall_curve_interactive",
    # SPC - static
    "control_chart",
    "x_range_chart",
    "moving_range_chart",
    "xbar_r_chart",
    "xbar_s_chart",
    "ewma_chart",
    "cusum_chart",
    "p_chart",
    "np_chart",
    "c_chart",
    "u_chart",
    "capability_histogram",
    "run_chart",
    "rule_violation_chart",
    "pareto_chart",
    "process_distribution",
    "zone_chart",
    "hotelling_t2_chart",
    "spc_dashboard",
    # SPC - interactive
    "control_chart_interactive",
    "x_range_chart_interactive",
    "moving_range_chart_interactive",
    "xbar_r_chart_interactive",
    "xbar_s_chart_interactive",
    "ewma_chart_interactive",
    "cusum_chart_interactive",
    "p_chart_interactive",
    "np_chart_interactive",
    "c_chart_interactive",
    "u_chart_interactive",
    "capability_histogram_interactive",
    "run_chart_interactive",
    "rule_violation_chart_interactive",
    "pareto_chart_interactive",
    "process_distribution_interactive",
    "zone_chart_interactive",
    "hotelling_t2_chart_interactive",
    "spc_dashboard_interactive",
    # SPC helpers
    "ControlLimits",
    "RuleViolation",
    "SPCConstants",
    "SPC_CONSTANTS",
    "CapabilityStats",
    "HotellingT2Result",
    "capability_summary",
    "hotelling_t2_summary",
    "detect_rule_violations",
    "get_spc_constants",
]
